### ISSUE TITLE
Consider not using constructors for API proxy creation

### ISSUE THREAD

**Issue by justinfagnani** [GoogleChromeLabs/comlink#1]
Just subjective opinion here, but a line like this:

```js
    // Note the usage of `await`:
    const app = await new api.App();
```

is a little confusing to me - it makes me think that `api.App` is a Promise, but then what type does the Promise resolve? I know it's a thennable that returns itself, but I think that ability of thennables probably goes over most people's heads. I think it'd be a little clearer with just a factory method:

```js
    // Note the usage of `await`:
    const app = await api.createApp();
```

**Comment by surma** [comment]
So would you disallow `new` altogether? It would make the RPC protocol a bit simpler 🤔 

The more I worked with this, the more I have gotten to like `await new ...` as it works with the mantra: “Whenever you are touching a Comlink’d proxy, use `await`.”

But I see your point that when you are trying to actually unpack the data structure in your head, it might not make sense right away.

**Comment by surma** [comment]
Also GoogleChrome/tasklets#9 might be relevant/of your interest

**Comment by surma** [comment]
Gonna close this for now :)
