### ISSUE TITLE
Support callbacks as function parameters

### ISSUE THREAD

**Issue by daniele-zurico** [GoogleChromeLabs/comlink#12]
Hi,
I'm not sure if I'm doing something wrong or there's a bug. What I'm doing is trying to use observable to receive the data.
Working example1:
```
public ngAfterViewInit(): void {
        this.main().then((ifr: any) => {
            const api = Comlink.proxy(ifr.contentWindow);
            (api as any).CommunicationChannel.getInstance().then((_instance) => {
                 _instance.setUserToken('123').then(() => {
                     _instance.getUserToken().then(res => console.log(res));
                });
            });
        });
    }

    private main(): Promise<any> {
        console.log('in');
        const ifr = document.querySelector('iframe');
        return new Promise((resolve) => ifr.onload = () => {
            resolve(ifr);
        });
    }
```

Iframe:
```
import {Comlink} from 'comlinkjs';
import 'rxjs/add/observable/of';
import {Observable} from 'rxjs/Observable';

/**
 * Create a communication channel between the different apps
 */

export default class CommunicationChannel {
    // Instance for the singleton class
    private static _instance: CommunicationChannel;

    // User token
    private _userToken;

    constructor() {
        if (CommunicationChannel._instance) {
            throw new Error('Error: Instantiation failed: Use SingletonClass.getInstance() instead of new.');
        }
    }

    /**
     * Create the instance
     */
    public static getInstance() {
        if (!CommunicationChannel._instance) {
            CommunicationChannel._instance = new CommunicationChannel();
        }
        return Comlink.proxyValue(CommunicationChannel._instance);

    }

    public setUserToken(userToken: string) {
        this._userToken = userToken;
    }


    public getUserToken(): string {
        return this._userToken;
        });
    }

}
// Expose listens for RPC messages on endpoint and applies the operations to rootObj
Comlink.expose({CommunicationChannel}, self.parent);
```

Changing in observable:
```
public ngAfterViewInit(): void {
        this.main().then((ifr: any) => {
            const api = Comlink.proxy(ifr.contentWindow);
            (api as any).CommunicationChannel.getInstance().then((_instance) => {
                const userToken = Observable.fromPromise(_instance.getUserToken());
                userToken.subscribe(res => console.log(res));

            });
        });
    }

    private main(): Promise<any> {
        console.log('in');
        const ifr = document.querySelector('iframe');
        return new Promise((resolve) => ifr.onload = () => {
            resolve(ifr);
        });
    }
```

Iframe same as before but change this method:
```
public getUserToken(): Observable<string> {
        return new Observable((observer) => {
            setInterval(() => {
                observer.next('hello');
            }, 1000);
        });
    }
```

Error:
```
comlink.es6.js:65 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'MessagePort': function (observer) {
            setInterval(function () {
                observer.next('hello');
            }...<omitted>... } could not be cloned.
    at MessagePort.<anonymous> (http://localhost:4201/vendor.bundle.js:2588:37)
    at <anonymous>
```

**Comment by daniele-zurico** [comment]
What I would to achieve is:
- the iframe do login and set the token
- the parent observe for the message received and get it.

In other word what I would avoid to do is:
```
public ngAfterViewInit(): void {
        this.main().then((ifr: any) => {
            setInterval(() => {
                const api = Comlink.proxy(ifr.contentWindow);
                (api as any).CommunicationChannel.getInstance().then((_instance) => {
                    _instance.getUserToken().then(res => console.log(res));
                });
            }, 1000);
        });
    }

    private main(): Promise<any> {
        const ifr = document.querySelector('iframe');
        return new Promise((resolve) => ifr.onload = () => {
            resolve(ifr);
        });
    }
```

**Comment by surma** [comment]
Ah, good catch. I was aware but forgot to document it in the README. 

As of now, function parameters need to be either structurally cloneable or transferable. Functions are neither. Therefore your callback won’t work. I am working on a good solution, but it’s not possible as of now.

(If you wanna hack for a bit: You could use Comlink in _both_ directions. Expose your callback to the iframe and hook it up to the Observable.

**Comment by surma** [comment]
I updated the README. Thanks for giving Comlink a spin! @daniele-zurico. I’ll get to this issue pretty quickly I reckon – it’s a central use-case.

I want to ask one thing of you, tho: Could you reduce your test cases in the future? I really can’t do much with snippets that use Angular and potentially other libraries or frameworks. The fewer the dependencies and SLOCs, the better :)

**Comment by daniele-zurico** [comment]
Oh sure.
I was trying to put entire snippet to make my code as much as possible easy to understand for you showing the part involved.
My plan is to create a post to show how to use this library and honestly I’m almost done with the code.
I just need to find the time to write the post and I think that will be useful for everyone because honestly I think that in the doc is not so easy to understand ( maybe is just me ).
However if you prefer, when the post is ready, you can link to it

**Comment by surma** [comment]
This has been fixed in 2191276b482625e3df7d0e54d210fd32d3ece5f1 (included in Comlink v2.1.0)

You only need to make sure you wrap your callbacks in `proxyValue`. 

Just keep in mind that these callbacks will end up being asynchronous functions on the other end, I so I am not sure if RxJS will handle this correctly by default. Enjoy!

**Comment by adrianromanko** [comment]
Running some tests with comlink...I tried passing an Observable object to the child iframe and then in the child I subscribed to that observable. Calling .subscribe(...) produced an error.

Code snippet:
await instance.proxyValues(Comlink.proxyValue({
                preferences$: this._getGlobalPreferencesObservable()
   }));

Error:
![image](https://user-images.githubusercontent.com/3165356/37179489-cbbf63b6-22f3-11e8-9724-04aa71decd48.png)

**Comment by surma** [comment]
Your callback needs to be wrapped into `proxyValue`.

```js
await preferences$.subscribe(Comlink.proxyValue(v => ... ));
```
