### ISSUE TITLE
TypeScript compilation fails for WebWorker

### ISSUE THREAD

**Issue by k7sleeper** [GoogleChromeLabs/comlink#123]
Compiling `comlink.d.ts` for a WebWorker fails with
```
Using tsc v2.8.3
node_modules/comlinkjs/comlink.d.ts(26,23): error TS2304: Cannot find name 'Window'.
node_modules/comlinkjs/comlink.d.ts(29,44): error TS2304: Cannot find name 'Window'.
```
My workaround is to remove "Window |" from method definitions for `proxy` and `expose`.

Dont we have another option?

**Comment by surma** [comment]
iiinteresting. Yeah, that’s my mistake. Not sure who I’m gonna fix it, but I’ll look into it!
