### ISSUE TITLE
Question about WebExtensions

### ISSUE THREAD

**Issue by DJWassink** [GoogleChromeLabs/comlink#129]
Hiya!

I was wondering if comlink would be able to work with WebExtensions, since in WebExtensions we have a ton of different "threads", communication because a hassle. comlink would sound like a nice solution but alas I run into some issues:

background.ts:
```ts
import {Comlink} from 'comlink';
class MyClass {
    logSomething() {
        console.info('hiya');
    }
}
Comlink.expose(MyClass, window);
```

popup.ts:
```ts
import {Comlink} from 'comlink';
chrome.runtime.getBackgroundPage(async bgPage => {
    if (bgPage) {
        const MyClass = Comlink.proxy(bgPage);
        const instance = await new (MyClass as any)();
        setInterval(() => {
            instance.logSomething();
        }, 5000);
    }
});
```

Now on the background page I get a total of 2 events before it crashes:

The first one goes ok and looks like this:
![image](https://user-images.githubusercontent.com/1822404/41040934-161ac090-699e-11e8-9eb4-d35a96bcbe27.png)

The second one however:
![image](https://user-images.githubusercontent.com/1822404/41040960-244a6242-699e-11e8-8fbd-fa5df92047ec.png)

since the next line slices the callPath property we end up with the following error/stacktrace:

```
Uncaught (in promise) TypeError: Cannot read property 'slice' of undefined at comlink.es6.js:71
(anonymous) 		@ comlink.es6.js:71
postMessage (async)
postMessage 		@ comlink.es6.js:180
(anonymous) 		@ comlink.es6.js:105
async function (async)
(anonymous) 		@ comlink.es6.js:66
15:29:08.559 
```

I was wondering if I'm doing something wrong or if WebExtensions (at least on chrome) has some implementation differences compared to other `postMessage` targets?

**Comment by oslego** [comment]
I tried debugging this one today and came out empty. I didn't get the error stated above, but no success either.

(Aside: I got a syntax error from `await new (MyClass as any)();` and used `await new MyClass()` instead)

I can confirm the two events occurring on the background page.
The message handler set in `pingPongMessage` doesn't seem to ever get called.

I am interested to learn why it seems to fail on web extensions. My use case is communication between a  background page and a DevTools extension page. Any leads welcome.

**Comment by dotproto** [comment]
I started looking into this and could not replicate the error in Chrome. I suspect that @DJWassink was using another browser & compiling TS to AMD or another browser-friendly format. I also tried to test in Firefox Developer Edition with dynamic import enabled & saw the same behavior. Edge doesn't have support dynamic import yet, so my test case simply failed there.

I'll need to spend some time digging into Comlink's messaging model before I have a good idea on what might need to change to support the extension use case.

**Comment by DJWassink** [comment]
I tried it again but without any compilation steps using the following code:

popup.js:
```js
import('./comlink.js').then(Comlink => {
    chrome.runtime.getBackgroundPage(async bgPage => {
        if (bgPage) {
            const MyClass = Comlink.proxy(bgPage);
            console.info(MyClass);
            const instance = await new MyClass();
            console.info(instance);
            
            setInterval(() => {
                instance.logSomething();
            }, 5000);
        }
    });
})
```

background.js:
```js
import('./comlink.js').then(Comlink => {
    class MyClass {
        logSomething() {
            console.info('hiya');
        }
    }
    Comlink.expose(MyClass, window);
})
```

And there isn't an error so indeed maybe that was because of the TypeScript compilation process.

However I now get stuck on the `await new MyClass();` part, the promise never resolves.

**Comment by surma** [comment]
@dotproto @DJWassink I am not sure this is actionable from my end. Going to close this issue, but please re-open if you think there is something I need to fix :)

**Comment by hackape** [comment]
I wrote a simple adapter for `chrome.runtime.port`, plain JS goes:

```
function webExtensionEndpoint(port) {
  const listeners = new WeakMap();
  return {
      postMessage: (message, transfer) => {
          port.postMessage(message);
      },
      addEventListener: (_, eh) => {
          const l = (data) => {
              if ("handleEvent" in eh) {
                  eh.handleEvent({ data });
              }
              else {
                  eh({ data });
              }
          };
          port.onMessage.addListener(l);
          listeners.set(eh, l);
      },
      removeEventListener: (_, eh) => {
          const l = listeners.get(eh);
          if (!l) {
              return;
          }
          port.onMessage.removeListener(l);
          listeners.delete(eh);
      },
  };
}
```

### usage:

**background.js**
```
// also works on `chrome.runtime.onConnectExternal`
chrome.runtime.onConnect.addListener((port) => {
  const api = {
    add(a, b) {
      return a + b;
    }
  };

  Comlink.expose(api, webExtensionEndpoint(port));
});
```

**popup.js**
```
const port = chrome.runtime.connect();
const endpoint = webExtensionEndpoint(port);
const api = Comlink.wrap(endpoint);

api.add(1, 1).then(v => console.log(v)); // --> 2
```

**Comment by hackape** [comment]
[chrome-extension-demo.zip](https://github.com/GoogleChromeLabs/comlink/files/3944657/chrome-extension-demo.zip)

Attach an extension for demo.
