### ISSUE TITLE
support exposing multiple classes/instances

### ISSUE THREAD

**Issue by lneir** [GoogleChromeLabs/comlink#132]
@surma great library...

we have been playing with your library and wondering if you have ideas/plans to support exposing multiple classes/instances...

For example...
```
// main.js
var worker = new Worker('worker.js');

const MyClass = Comlink.proxy(worker, 'MyClass');
const instance = await new MyClass();
await instance.logSomething(); // logs “myValue = 42”

const OtherClass = Comlink.proxy(worker, 'OtherClass');
const otherInst = await new OtherClass();
await otherInst.logSomethingElse(); // logs “myOtherValue = 43”
```

```
// worker.js
const myValue = 42;
class MyClass {
  logSomething() {
    console.log(`myValue = ${myValue}`);
  }
}
Comlink.expose(MyClass, 'MyClass', self);

class OtherClass {
  logSomethingElse() {
    console.log(`myOtherValue = ${myValue + 1}`);
  }
}
Comlink.expose(OtherClass, 'OtherClass', self);
```

i played around and one simple method to implement this is to pass extra parameter string to proxy and expose method (as you can see in example above).

wondering if you have some thoughts on this use case and if this is on your roadmap?

thanks.

**Comment by surma** [comment]
I didn’t want to increase the API surface so I just made sure you can use destructuring:

```
// worker.js
// ...
Comlink.expose({MyClass, OtherClass}, self);
```

```
// main.js
var worker = new Worker('worker.js');

const {MyClass, OtherClass} = Comlink.proxy(worker);
// ...
```

Is that good enough? If not, feel free to re-open :)

**Comment by lneir** [comment]
awesome sauce...  would be good to add example to documentation.

also like that you can flip things around and expose classes/instance from main thread - would be good to document this as well.
