### ISSUE TITLE
Document the requirement of "async functions"

### ISSUE THREAD

**Issue by fnlctrl** [GoogleChromeLabs/comlink#146]
Currently the document only includes "Proxy" requirement, but it caught me off-guard that async functions are also used in the code.

[Proxy support](https://caniuse.com/#search=proxy): iOS >= 10.2
[Async function support](https://caniuse.com/#search=async%20functions): iOS >= 10.3

So even if proxy is polyfilled, one must also take care of async functions support too. This incurs the inevitable configuration of babel and regenerator, which is not always desirable. 

It would be great if they can be replaced with plain functions returning promises. If not then it should be documented as well in the readme, like proxy polyfill.

**Comment by surma** [comment]
Async functions are mostly syntactic sugar in nature. If you are targeting a browser without async function support, you should be able to babel Comlink without issues (if not, please let me know!)

However, I am not going to rewrite Comlink with synchronous functions considering:
- it will increase the file size
- it will make the code harder to maintain 
- [async functions are supported in the last 2 version of all major browsers](https://caniuse.com/#feat=async-functions)
