### ISSUE TITLE
Q: async transformation to native promise

### ISSUE THREAD

**Issue by wardpeet** [GoogleChromeLabs/comlink#161]
we are implementing comlink for site <-> iframe communication. Sadly we still need to support IE11 which has no support for async await. Async-await transpiling with babel adds about 28kb (unminified, nogzip) to the bundle.

I see the async keyword used twice. It it ok to convert them to native promises so we don't take this perf hit?
https://github.com/GoogleChromeLabs/comlink/blob/master/comlink.ts#L178
https://github.com/GoogleChromeLabs/comlink/blob/master/comlink.ts#L211

I don't mind doing the work.

**Comment by surma** [comment]
That’s a super interesting find. If you wanna whip a PR, it’d be highly appreciated!

**Comment by wardpeet** [comment]
thanks! i'll cook something up

**Comment by wardpeet** [comment]
@surma I see that you're also using generators which still keep the bundle big.
async - await compiles to generators so not sure if you're ok with that

**Comment by wardpeet** [comment]
When removing async & await from comlink I get this result from bundlesize when it gone through https://babeljs.io/repl with ie11 enabled as a browser
` PASS  dist/comlink.js 22.17KB (no compression)`

before it was
` PASS  dist/comlink.js: 25.31KB (no compression)`

I saw that it was also using a generator function to iterateAllProperties. I could work around the generator and make it es5 compliant but we "penalize" all the browsers which might not worth it. I could see how much it adds to the bundlesize to see how hard we "penalize" these browsers. 

wdyt?

**Comment by wardpeet** [comment]
we could always go for the nomodule trick for ie in our code 👍

**Comment by surma** [comment]
Hm, I think it’s possible to implement `iterateAllProperties` with a `for` loop without a lot more code. If we are going for ES5, we should go all the way. Just removing async/await but not generators doesn’t help a lot, I think.

Happy to take a “Make it all ES5” PR, provided functionality remains and it’s not to much of an increase. You currently have a 15% increase, but it’s not minified, which is what we need to look at (ideally, also a separate gzip number). Sounds good?

**Comment by git-jiby-me** [comment]
@surma @wardpeet FYI https://github.com/GoogleChromeLabs/comlink/pull/199 avoid async await, generators and iterators in source. With that tsc does not inject any helpers and the size does not increase much

**Comment by surma** [comment]
The next major version of Comlink doesn’t use generators anymore (but still promises). If you want, feel free to take a look at the branch `v4` or at the npm release `comlink@next`.

**Comment by wardpeet** [comment]
thanks for notifying, I actually forgot about this one. Using https://github.com/rpetrich/babel-plugin-transform-async-to-promises allowed us to convert async await without generators so this wasn't blocking anymore
