### ISSUE TITLE
Support OffscreenCanvas as a transferable

### ISSUE THREAD

**Issue by dougmoscrop** [GoogleChromeLabs/comlink#165]
I'm not sure the best way to implement or handle this, especially since I've never used TypeScript before.

I hacked this together: https://github.com/dougmoscrop/comlink/commit/edd4004120ec6d3a155fa537f0c073b20bbc3202#diff-7c90bf97a77d0d5f32703d33f3878977R130

**Comment by surma** [comment]
You just have to add it to the `TRANSFERABLE_TYPES` array right above. Happy to accept an PR :)

**Comment by dougmoscrop** [comment]
When I did that, some tests failed because it's not universally supported in e.g. Firefox
