### ISSUE TITLE
Changelog 

### ISSUE THREAD

**Issue by daniele-zurico** [GoogleChromeLabs/comlink#18]
It could be useful to have a changelog.md file to see what is changed from the previous version.
For example from 2.1 to 2.2 no idea what is the benefit to upgrade

**Comment by surma** [comment]
Yeah, I might start doing that, but for now the project is too young to make that effort. If you want to see what changed, use `git log` (or the corresponding GitHub feature) to see the commits between the tags.

Example: https://github.com/GoogleChromeLabs/comlink/compare/v2.1.0...v2.2.0
