### ISSUE TITLE
Error: endpoint does not have all of addEventListener, removeEventListener and postMessage defined

### ISSUE THREAD

**Issue by koalalorenzo** [GoogleChromeLabs/comlink#190]
My project is split into two modules, one for the web worker and one for the SPA.
In my Worker I have something similar to the following code:

```
import * as Comlink from 'comlinkjs'

// [...] Import other stuff


export class Integration {
  ping = () => Promise.resolve('pong')
 // Other stuff here
}

console.log('[Worker] Starting API connection')
customEvent.init().then(() => {
  console.log('[Worker] Connected to the network')
})

Comlink.expose(Integration, self)
```
This gets transpired and packed with Babel 7 and Webpack.

Then In my SPA instance I have
```
import * as Comlink from 'comlinkjs'
const workerProcess = typeof Worker !== 'undefined' ? new Worker('web-worker.js') : {}
const service = Comlink.proxy(workerProcess)

function isWorkerAlive () {
  return service.ping().then((value) => value === 'pong')
}
```

But when I load it, I get an error:

```
Error: endpoint does not have all of addEventListener, removeEventListener and postMessage defined
```

What am I doing wrong?
In the documentation there is no explanation on how to import the module, just how to install it. it is not clear to me and I am not sure if I am missing something. Can anybody help?

**Comment by surma** [comment]
Are you sure webpack is not doing some eager evaluation magic? For example the `typeof Worker !== 'undefined' looks suspicious. What does the compiled output look like?

**Comment by koalalorenzo** [comment]
@surma sorry, don't close this :) 
The `typeof Worker` was done as a workaround to some testing. Removing it doesn't change much.

Typescript + Webpack

**Comment by surma** [comment]
I never got a reply so I figured this was abandoned :D

I’m still curious why you are doing this:

```js
const workerProcess = typeof Worker !== 'undefined' ? new Worker('web-worker.js') : {}
```

If you have a separate worker file, why are you detecting workers here? And also, if `typeof Worker === 'undefined'`, then `workerProcess = {}`, and that will of course throw, as that is not valid endpoint to pass to `Comlink.proxy()`.

> In the documentation there is no explanation on how to import the module, just how to install it. 

There is nothing special in importing Comlink. You did it correctly.

Additional side note: Do you know about [worker-plugin](https://github.com/GoogleChromeLabs/worker-plugin)?
