### ISSUE TITLE
[question] - npm "comlink" vs "comlinkjs"

### ISSUE THREAD

**Issue by shayc** [GoogleChromeLabs/comlink#191]
Just installed `comlink` via npm, I noticed there's another package `comlinkjs`.
Wanted to know what package to install, I don't want to get "stuck" with an unmaintained package when you inevitably decide to focus on one.. (?)

**Comment by surma** [comment]
They are identical and both maintained by me :)

(I started with comlinkjs, but was able to get comlink later)

**Comment by drive4thecause** [comment]
For anyone googling, this is no longer true. Don't use comlinkjs unless you want to spend some time trying to figure out why things aren't working. :)

**Comment by surma** [comment]
Good shout. I should officially deprecate comlinkjs

**Comment by surma** [comment]
Done :)
