### ISSUE TITLE
Add the ability to enumerate exposed objects on the proxy side

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChromeLabs/comlink#20]
It would be useful to discover the classes and functions that have been exposed to the proxy.

**Comment by surma** [comment]
Hm, that’s gonna be tricky.

ES6 Proxies have a [`ownKeys` handler](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/ownKeys), but it needs to return an enumerable object _synchronously_. There doesn’t seem to be a way to sneak in asynchronicity. 

I _could_ transfer the list of keys on setup and keep the list up to date by using proxies on the `expose` side, but that seems pretty complicated and actually somewhat race-y.
