### ISSUE TITLE
Publish source maps and declaration maps

### ISSUE THREAD

**Issue by felixfbecker** [GoogleChromeLabs/comlink#204]
Enabling `sourceMap` allows stepping into comlink code when debugging and to have stack traces that point to the real source, if the source is also included in the npm package either as files or inline in the source map.
`declarationMap` in tsconfig.json allows tools to map the .d.ts files back to the source, which for example allows cross-repository go-to-definition and find-all-references on [sourcegraph.com](https://sourcegraph.com).

This is currently difficult to add because the package.json is copied into `dist/`, and TypeScript would then point to `../comlink.ts` as the source, which doesn't exist because `..` would be `node_modules`. Why not publish the package root? Comlink is just a single file so it's always imported through the main import anyway.

**Comment by surma** [comment]
I should consider just publishing the entire root. It’ll be a breaking change, but I’ll look into it for the next release.

**Comment by felixfbecker** [comment]
I agree. Should be non-breaking since comlink only has a single file that is the `main`/`types` field, which will continue to work with the same imports if just pointed to the files in `dist/`

**Comment by surma** [comment]
The next major of Comlink is doing this a lot better, I think. It‘s on the `v4` branch and released to npm under `comlink@next`. Please take a look :)

**Comment by surma** [comment]
Closing this as v4 is now live!
