### ISSUE TITLE
gitignore dist

### ISSUE THREAD

**Issue by felixfbecker** [GoogleChromeLabs/comlink#222]
It's best practice to not commit compiled outputs because they only create unneeded diffs and merge conflicts, and there's a risk of the dist files getting out of sync with the source.

**Comment by surma** [comment]
Yeah, I am planning to change this with the next major release (but it’s a breaking change so it’s gonna be a while0.

**Comment by felixfbecker** [comment]
How is it a breaking change?

**Comment by surma** [comment]
Me (amongst other people) use the GitHub repo as a npm dependency. So I consider parts of my folder structure part of the API.

**Comment by felixfbecker** [comment]
Yeah, but when you remove it, the old commit will still have the files. Unless you are pointing to `master`, in which case you could never ever change it.

**Comment by surma** [comment]
I expect people use the GitHub repo URL with version tags. 

So all I’m saying is that I can only do this change with a major version release (b/c/ a breaking change). So I wanna do all the breaking changes I have lined up in one go :)

**Comment by surma** [comment]
The next major of Comlink is not committing `dist` anymore 🎉 (See `v4` branch)

**Comment by surma** [comment]
Closing this as v4 is now live!
