### ISSUE TITLE
 proxied instance returned via a promise fails to work...

### ISSUE THREAD

**Issue by lneir** [GoogleChromeLabs/comlink#232]
In example below (using master version of comlink) the call to `await instance.logSomething()` in the resolved promise fails - it appears passing item through resolve calls through to comlink but gets back an incorrect object.  Any ideas why this might be happening?   Thanks.

```js
// main.js
import * as Comlink from './comlink.js';

const pr = new Promise(async (resolve) => {
    const items = Comlink.proxy(new Worker("worker.js", {type: "module"}));
    const item2 = items['class2']; 
    resolve(item2);
});

pr.then(async (instance) => {
    // this fails with error: TypeError: instance.logSomething is not a function
    await instance.logSomething();
});

// worker.js
import { expose } from "./comlink.js";

const myValue = 42;

class MyClass {
    logSomething() {
        console.log(`myValue = ${myValue}`);
    }
}

const exposedItems = {
    class1: new MyClass(),
    class2: new MyClass(),
}
expose(exposedItems, self);
```

**Comment by surma** [comment]
This is an interesting corner case. 

If you wrote it like this, it will work:

```js
const items = Comlink.proxy(new Worker("comlink_232_worker.js", {type: "module"}));
    const item2 = items['class2']; 
    await item2.logSomething();
```

The problem is that `resolve(item2)` will implicitly call `.then()` on `item2`, which Comlink sees as a signal to transfer the value. So it tries to structurally clone the instance of `MyClass` and all you get on the other side is an empty object.

There’s two ways to fix it.

1. Mark them as values that should always be proxied:

```js
const exposedItems = {
    class1: proxyValue(new MyClass()),
    class2: proxyValue(new MyClass()),
}
```

2. Don’t resolve `item2` itself but wrap it in an object to avoid calling `.then()` on it:

```js
const pr = new Promise(async (resolve) => {
    const items = Comlink.proxy(new Worker("comlink_232_worker.js", {type: "module"}));
    const item2 = items['class2']; 
    resolve({instance: item2});
});

pr.then(async ({instance}) => {
    await instance.logSomething();
});
```

HTH

**Comment by lneir** [comment]
believe i see now... comlink object returned (item2 in this case) is 'thenable' [comlink get](https://github.com/GoogleChromeLabs/comlink/blob/master/comlink.ts#L492), so like doc says here: [mdn promise resolve](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve)  it will follow that "thenable".

thanks for help.
