### ISSUE TITLE
Explain/give examples when a web worker makes sense

### ISSUE THREAD

**Issue by daKmoR** [GoogleChromeLabs/comlink#246]
Given that a web worker is not "free" and you need to "hop" you data around it should be explained when and when not to use web workers.

Even though they are available for quite some time the adoption ratio is pretty slow (iirc). So given a little head start seems like a good idea 🤗 

This library makes it almost "too easy" to use them (which is awesome) but I'm still struggling to find a good use case for them in my day to day tasks 🙈

**Comment by surma** [comment]
To me, the question is not really “when should I use workers?” but rather “when should I _not_ use workers?”.

I have this section in the v4 README (not sure if you saw that):

> On mobile phones, and especially on low-end mobile phones, it is important to keep the main thread as idle as possible so it can respond to user interactions quickly and provide a jank-free experience. **The UI thread ought to be for UI work only**. WebWorkers are a web API that allow you to run code in a separate thread.

To elaborate a bit: If you take a look at native platforms, they always restrict the UI thread to UI work — everything else has to run in different threads. And it works! Android and iOS are doing much much better (on average) at having a responsive, non-janky UI experience. The web can do that, too, if we just do the same thing.

So my recommendation is: Go nuts. Use workers!

**Comment by daKmoR** [comment]
thxxx and yeah I really missed that (was looking at master) 🙈 

I'm still a little unsure e.g. let's take a concrete example:
Parsing of money amounts (from strings to numbers)... 
e.g. there is an input and the users pasts an arbitrary string in there and we want to take the best "guess" on what he entered... 

it's just `parseAmount(valueString)` nothing super crazy but still
- we check for separators
- if there are multiple separators and we can't for sure say if which is which we check with locale
- ...

could/should this be a function in a web worker? or is the hopping "heavier" than the gain by offloading it from the main thread?

**Comment by surma** [comment]
It depends, really. But here’s how I think about it:

A user interaction needs a response in < 100ms. The hops are not free but they are also not expensive (unless you have a massive object to send, and I haven’t hit that boundary yet). By putting your business logic in a worker, even if it is this simple, is that you keep your main thread free even on low-end devices.

I am currently developing on an Android Go phone and a KaiOS phone and just calculating styles sometimes takes >30ms, twice the frame budget. So ever ms that you can move somewhere else counts. And with Comlink it really shouldn’t be painful to do so :)
