### ISSUE TITLE
[v4] comlink.d.ts(14,26): error TS2307: Cannot find module './protocol.js'.

### ISSUE THREAD

**Issue by lacolaco** [GoogleChromeLabs/comlink#250]
Version 4.0.0-alpha.7

`dist/umd/comlink.d.ts` in the published package is broken. It imports `'./protocol.js'` but `protocol.js` doesn't exist. 

https://unpkg.com/comlink@4.0.0-alpha.7/dist/umd/comlink.d.ts

**Comment by surma** [comment]
Good catch, @lacolaco! Thanks for flagging that.

I pushed `4.0.0-alpha.8` which _should_ fix that issue. Can you please confirm?

**Comment by lacolaco** [comment]
@surma the original problem seems solved. thank you!
And now I'm in another situation. it looks a breaking change in typing.

```
ERROR in src/app/worker/markdown.ts(18,18): error TS2345: Argument of type 'Window' is not assignable to parameter of type 'Endpoint'.
  Types of property 'postMessage' are incompatible.
    Type '(message: any, targetOrigin: string, transfer?: Transferable[]) => void' is not assignable to type '(message: any, transfer?: any[]) => void'.
      Types of parameters 'targetOrigin' and 'transfer' are incompatible.
        Type 'any[]' is not assignable to type 'string'.
```

```
import * as marked from 'marked';
import { expose } from 'comlink';

export class Markdown {
  compile(source: string) {
    return new Promise<string>((resolve, reject) => {
      marked(source, (err, result) => {
        if (err) {
          reject(err);
          return;
        }
        resolve(result);
      });
    });
  }
}

expose(Markdown, self); // <---- self is not compatible to Endpoint
```

I think this is not by design, right?

**Comment by surma** [comment]
Comlink v4 has loads of breaking changes :D

Before I start: [`expose()` passes `self` by default now](https://github.com/GoogleChromeLabs/comlink/blob/36fbc091dd86446349f6dc9e81a5f66e032a2d72/src/comlink.ts#L95).

But this looks more like TypeScript isn’t aware that you are in a worker context. A simple

```ts
declare var self: DedicatedWorkerGlobalScope;
```

should force TypeScript to assume a worker context.

HTH

**Comment by lacolaco** [comment]
It's not easy to solve. 

- `DedicatedWorkerGlobalScope` is declared in `webworker` lib.
- `self` is declared in both of `dom` and `webworker`
  - so, `dom` and `webworker` are incompatible

![image](https://user-images.githubusercontent.com/1529180/54727600-00bf9080-4bbc-11e9-9cad-ddc0c8e8470d.png)

```
declare var self: DedicatedWorkerGlobalScope;
```

This line is not valid in `dom` context because `DedicatedWorkerGlobalScope` is only in `webworker` context. It's exclusive.

So, if Comlink is used within usual frontend projects, this restriction requires developers to separate tsconfig.json and change transpilation workflow.

**Comment by lacolaco** [comment]
casting as `any` is the only solution in this case...

```ts
expose(Markdown, self as any);
```

**Comment by surma** [comment]
Yeah, this is [a long-standing issue with TypeScript](https://github.com/Microsoft/TypeScript/issues/20595), but this problem already existed with Comlink v3.

FWIW, whenever you use bundlers like Rollup you don’t get these errors.

> casting as any is the only solution in this case...

Not true :D That is the reason why I set `self` to be the default value for `expose()`, so this will compile just fine:

```ts
expose(Markdown);

```

**Comment by lacolaco** [comment]
@surma I didn't know about the default value! It's perfect for me. Thank you!

The original issue is solved. I close here.
