### ISSUE TITLE
Maintenance of the webpack loader

### ISSUE THREAD

**Issue by JesseFarebro** [GoogleChromeLabs/comlink#253]
It's been almost a year since v3.0 was released and the webpack loader still hasn't been bumped to version 3. With version 4 on the horizon, I was wondering if it would be possible to finally get some love for the webpack loader?

There is a PR open in the loader project currently https://github.com/GoogleChromeLabs/comlink-loader/pull/11.

**Comment by surma** [comment]
I didn’t write comlink-loader, @developit did.

That being said, I think it’s saner to deprecate comlink-loader and point to the much more generic [worker-plugin](https://github.com/GoogleChromeLabs/worker-plugin). It should make workers with webpack work like a charm.

@developit WDYT?

**Comment by mrfelton** [comment]
Can Comlink be used in conjunction with worker-plugin? It seems like they are entirely different things. worker-plugin seems to just loads workers where as Comlink actually proxies things and makes working with workers easy. Am I missing something?

**Comment by surma** [comment]
You are right, they solving completely different problems — but that is a sign that they are work _well_ together, no?

worker-plugin teaches webpack to understand the Worker constructor. You don’t need to create a separate entry point or anything in your webpack config to make that work. But it just gives you a normal worker instance.

Comlink can be used on top of that to give you the ergonomics.

We are using this very combination in [Squoosh](https://squoosh.app).

**Comment by JesseFarebro** [comment]
@surma I have resorted to using webpack's worker loader and comlink. The combination works very well and hopefully, that is the recommendation going forward instead of using the comlink webpack loader.

**Comment by surma** [comment]
Going to close this as it doesn’t seem actionable anymore.

Please re-open if you disagree.

**Comment by developit** [comment]
Apologies for the radio silence. I would indeed recommend going with worker-plugin + comlink. It's a little less magic and avoids the tradeoffs comlink-loader comes with.

**Comment by NicolasRannou** [comment]
@JesseFarebro could you point us out to a working demo of the implementation? I keep running into random issues... :(
