### ISSUE TITLE
An example using Service Worker?

### ISSUE THREAD

**Issue by alastaircoote** [GoogleChromeLabs/comlink#27]
When I saw this I assumed I could slot a service worker in the same place a web worker was being used in the example, but service workers don't have `self.postMessage`, so it doesn't work. I've got it working now by hooking up the proxy through a MessagePort in a message event - is that the best way to do it?

Either way, it would be great to have an example showing the best practise for this.

**Comment by surma** [comment]
You are right, a ServiceWorker doesn’t have `self.postMessage` at there might be potentially multiple open windows. So yeah, sending a MessagePort is one good solution. Another option would be to get the actual window object using `self.clients.get()` or `self.clients.matchAll()`.

It’s probably a good idea for me to write an example for this.

Hope this helps.

**Comment by surma** [comment]
I am curious, tho. What is your current use-case with Comlink + ServiceWorker? What are you exposing?

**Comment by alastaircoote** [comment]
I'm using Notification APIs that are only available in a SW (as far as I know), as well as checking progress of caching events. I know it's not a core use of Comlink but I've found it useful so far!

**Comment by surma** [comment]
You can use Notification API without SW :) 

Progress of caching is definitely an interesting use case.

**Comment by alastaircoote** [comment]
AFAIK you can show a notification, but can't for example call getNotifications():

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/getNotifications

Would love to be wrong though :)

**Comment by surma** [comment]
That’s correct. I thought you just wanted to show notifications

**Comment by gruns** [comment]
+1 for a canonical, best-practice example of establishing a comlink <-> ServiceWorker connection.

**Comment by jeffposnick** [comment]
I'm trying to follow the recommendation in https://github.com/GoogleChromeLabs/comlink/issues/27#issuecomment-337350587:

> Another option would be to get the actual window object using `self.clients.get()` or `self.clients.matchAll()`.

While the `WindowClient` interface has a `postMessage()` method, it doesn't have `addEventListener()` or `removeEventListener()`, so trying to do something like:

```js
class RunInSW {
  // ...
}

self.addEventListener('message', async (event) => {
  if (event.data === 'init-comlink') {
    const clients = await self.clients.matchAll();
    for (const client of clients) {
      Comlink.expose(RunInSW, client);
    }
  }
});
```

leads to

```sh
Error: endpoint does not have all of addEventListener, removeEventListener and postMessage defined
```

**Comment by jeffposnick** [comment]
Here's what I've come up with so far, which seems to work:

In the `window` context:
```js
navigator.serviceWorker.addEventListener('controllerchange', () => {
  const channel = new MessageChannel();
  navigator.serviceWorker.controller.postMessage(channel.port2, [channel.port2]);
  window._runInSW = Comlink.proxy(channel.port1);
});
```

In the SW context:
```js
self.addEventListener('message', (event) => {
  if (event.data instanceof MessagePort) {
    Comlink.expose(api, event.data);
  }
});
```

**Comment by surma** [comment]
I think I like your solution better. I’ll adjust my PR :)
