### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by mysticatea** [GoogleChromeLabs/comlink#273]
I have found v4 release, but I'm not sure what breaking changes are. Commit log is noisy because of a ton of renovate's PRs and merge commits.

Would you provide a changelog?

**Comment by guanzo** [comment]
Yes please provide a changelog.

**Comment by surma** [comment]
Thanks for flagging this! I added a [CHANGELOG.md](https://github.com/GoogleChromeLabs/comlink/blob/master/CHANGELOG.md) to the repository. Let me know if that is helpful :)
