### ISSUE TITLE
Edge kills proxied workers

### ISSUE THREAD

**Issue by lgfrbcsgo** [GoogleChromeLabs/comlink#303]
I watched the [HTTP 203 episode on silly browser hacks](https://www.youtube.com/watch?v=ViyTYEv9dM8) just now. Funnily enough, I found the same bug in Edge two days ago and thought I'd share it here.

Basically, if the proxy is holding the only reference to the worker, it will kill it randomly.
I don't think this can be solved by comlink.

**Comment by surma** [comment]
(Sorry for not replying, this must have gotten lost in my email...)

Interesting. I haven't seen this with Edge, only with iOS Safari. For other people finding this issue, the workaround is as ugly as it is effective:

```js
const worker = new Worker("./worker.js");
// Put the worker on the global to prevent its termination
self._workerlol = worker;
//or globalThis._workerlol = worker;
const proxy = Comlink.wrap(worker);
```

**Comment by surma** [comment]
Closing this as there's nothing I can really do here at the library level.
