### ISSUE TITLE
Typings don't seem to match usage.

### ISSUE THREAD

**Issue by pmkroeker** [GoogleChromeLabs/comlink#304]
I've set up as per the example in the README:
```typescript
// CompareWorker is loaded through webpack worker-loader
const workerBase = new CompareWorker();
const CompareWork = Comlink.wrap<Compare>(workerBase);
const CompareOr = await new CompareWork();
```
But when I go to create the instance I get this TS error on line 4:
```
Cannot use 'new' with an expression whose type lacks a call or construct signature.ts(2351)
```

The return type from `wrap` is an interface with the methods of the class passed through the function. As this doesn't have a call signature it prompts with an error. TS still compiles fine, but the logged errors are frustrating when the usage is correct.

**Comment by pmkroeker** [comment]
I fixed it using
```typescript
const workerBase = new CompareWorker();
const CompareWork = await Comlink.wrap<Compare>(workerBase);
```
Which looks like how its supposed to be done.

I think just the picture of usage in the README is incorrect.

**Comment by surma** [comment]
I am not sure what your types are, but 

```ts
const CompareWork = Comlink.wrap<Compare>(workerBase);
```

means that `CompareWork` will be an _class instance_ of `Compare`. My hunch is that you actually want `CompareWork` to be the _class_ `Compare` with which you can create new instances using `new`.

The typical fix for this is 

```ts
const CompareWork = Comlink.wrap<typeof Compare>(workerBase);
```

**Comment by pmkroeker** [comment]
Oh right, yes that's exactly what I was looking for thanks!

Friday afternoon coding is never the smoothest.

**Comment by pmkroeker** [comment]
Thanks again, made the change this morning and it worked perfectly! Thanks @surma for the help! For some reason I was trying to use `const CompareWork = Comlink.wrap<instanceof Compare>(workerBase);` 😝

**Comment by linonetwo** [comment]
```ts
const CompareWork = Comlink.wrap<typeof Compare>(workerBase);
```
won't work, it errors `Property 'increment' does not exist on type 'Remote<typeof MyClass>'`

**Comment by linonetwo** [comment]
```ts
const CompareWork = Comlink.wrap<Compare>(workerBase);
```

Gives the correct type, it warp all methods in Promise, but error in runtime `Uncaught (in promise) TypeError: Cannot read property 'apply' of undefined`

**Comment by surma** [comment]
For future reference, if you think something is wrong, please put an example on a Glitch. These partial code snippets are not very helpful for me to figure out where things are going wrong. That being said, I think this is all working as intended and you are merely getting your types mixed up a bit :D

It all depends on what you are passing to `expose()`.

* If you are using `Comlink.expose(MyClass)`, you are exposing the _class_ and the corresponding counterpart is `const thing = Comlink.wrap<typeof MyClass>(worker)`. `thing` is now the _class_ (not an instance!), meaning you can't call any methods (like `increment`) until you create an instance using `const instance = await new thing()`.
* If you are using `Comlink.expose(new MyClass())`, you are exposing an _instance_ and the corresponding counterpart is `const thing = Comlink.wrap<My class>(worker)`. `thing` is now an instance and you can call methods straight away.

If you still think this is wrong please re-open and give me a full sample showing me the wrong behavior.

**Comment by linonetwo** [comment]
Thank you for the explanation, I apologize for my rude.

Make it worked now, here are my working examples:

```tsx
/// aaa.ts
export class MyClass {
  public _counter: number;

  constructor(init = 0) {
    console.log(init);
    this._counter = init;
  }

  get counter() {
    return this._counter;
  }

  public increment(delta = 1) {
    this._counter += delta;
  }
}


/// aaa.worker.ts
import * as Comlink from 'comlink';

import { MyClass } from './aaa';

Comlink.expose(MyClass);
export default null as any; // to import it, tsc need something to be exported

/// App.tsx
import * as Comlink from 'comlink';

import AAAWorker from './aaa.worker';
import { MyClass } from './aaa';

const MyClassType = Comlink.wrap<typeof MyClass>(new AAAWorker());
(async function() {
  const aaa = await new MyClassType();
  await aaa.increment();
  console.log(await aaa.counter);
})();
```

And

```tsx
/// aaa.ts
export class MyClass {
  public _counter: number;

  constructor(init = 0) {
    console.log(init);
    this._counter = init;
  }

  get counter() {
    return this._counter;
  }

  public increment(delta = 1) {
    this._counter += delta;
  }
}


/// aaa.worker.ts
import * as Comlink from 'comlink';

import { MyClass } from './aaa';

Comlink.expose(new MyClass());
export default null as any;

/// App.tsx
import * as Comlink from 'comlink';

import AAAWorker from './aaa.worker';
import { MyClass } from './aaa';

const aaa = Comlink.wrap<MyClass>(new AAAWorker());
(async function() {
  await aaa.increment();
  console.log(await aaa.counter);
})();
```

`worker-loader` is used.

Advertisement: To use `worker-loader` in CRA, try [rescript-worker-loader](https://github.com/linonetwo/rescript-worker-loader)
