### ISSUE TITLE
Comlink without using async/await anywhere still works

### ISSUE THREAD

**Issue by andraz** [GoogleChromeLabs/comlink#335]
I am experimenting with `immer` and realized that I can simply skip all async/await code, and everything will still work (even when the callbacks get delayed by settimeout).

https://codesandbox.io/s/immer-web-worker-gs5pv

What is the benefit of using async/await?

**Comment by surma** [comment]
Function calls only need `await` (or a `.then()`) if you are interested in the return value of that function. Properties, however, _need_ an `await` (or `.then()`) to get their value. This has to do with the fact that Comlink coalesces a sequence of property getters into one RPC message to avoid creating unnecessary `MessagePort`s.
