### ISSUE TITLE
Problem with 2 way communication to & from iframe

### ISSUE THREAD

**Issue by ssured** [GoogleChromeLabs/comlink#34]
I extended the iframe example a little, see  https://gist.github.com/ssured/79471d3e78332e60567012969f716355

When running I get proper results and 2 errors:
![image](https://user-images.githubusercontent.com/2558804/32168621-a9a20860-bd6d-11e7-9619-88c7dad6c986.png)

Line 67 refers to https://github.com/GoogleChromeLabs/comlink/blob/c2be4cac3619414b584c7c41bda2e4086dd7cf13/comlink.ts#L190

Changing this line: https://github.com/GoogleChromeLabs/comlink/blob/c2be4cac3619414b584c7c41bda2e4086dd7cf13/comlink.ts#L187

to `if (!event.data.id || !event.data.callPath)` fixes the problem, but I really don't know if thats OK.

Thanks for the library. Any help on getting 2 way communication done is greatly appreciated.

**Comment by surma** [comment]
Ah, you can’t re-use the same `postMessage` channel for multiple `expose()` calls. It’s been “used up” already. Maybe that’s something I should change. I’ll think about it.

For now, I’d recommend just defining a function where you pass the parentApi object as a parameter and wrap it in `proxyValue()`. I whipped up a Glitch ([demo](https://comlink-issue-34.glitch.me/), [code](https://glitch.com/edit/#!/comlink-issue-34)) using your code as a starting point.

Let me know if that helps :)

**Comment by ssured** [comment]
Thanks @surma. It totally helps 👍 Dunno but for me 2 way communication is essential to talk to a remote webpage and back. Your code exposes a really nice way to set this up between browsers. Maybe nice to add to the README?
I did not test yet in a 'real' scenario yet though, as I was hitting cross-origin issues when talking from our company page to a `github.io` hosted static PWA.

Thanks for your help!
