### ISSUE TITLE
React-redux store example: proxy susbcribe callback fails

### ISSUE THREAD

**Issue by sladiri** [GoogleChromeLabs/comlink#341]
Hi,

Thank you for this great project.

I tried to put a Redux store inside a worker with Comlink according to [Surma's article](https://dassur.ma/things/react-redux-comlink/).
The code fails inside the proxy wrapper with the error below. I do use a proxy for the callback. My code is [here](https://github.com/sladiri/redux-saga-threaded/tree/ee2d9b1adab532d499276f658dadcd0b84fc995e).

**EDIT:** I added a commit and changed the link to point to the old commit with thie error. Actually in the next commit I changed the implementation so that the worker exchanges diffs with Immer. Now I use the reducer twice (in main and in worker) and pass actions between them and the error is gone. I **think** this is what Surma described, how to prevent React from rerendering everything, and this was my intention anyway. Still I do not understand why the error happens.

```js
comlink.mjs:143 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on
 'DedicatedWorkerGlobalScope': function unsubscribe() {
      if (!isSubscribed) {
        return;
      }

      if (isDispatching) {
       ...<omitted>... } could not be cloned.
    at http://localhost:3000/static/js/0.chunk.worker.js:4239:8
``` 

```js
import { proxy } from "comlink";

export const remoteStoreWrapper = async (remoteStore) => {
  const subscribers = new Set();
  let latestState = await remoteStore.getState();

  remoteStore.subscribe(
    proxy(async () => {
      latestState = await remoteStore.getState();
      subscribers.forEach((f) => f());
    }),
  );

  return {
    dispatch: (action) => remoteStore.dispatch(action),
    getState: () => latestState,
    subscribe(listener) {
      subscribers.add(listener);
      return () => subscribers.delete(listener);
    },
  };
};
```

**Comment by sladiri** [comment]
I am sorry, since yesterday I did a `npm i comlink@latest` and now it works.

**Comment by sladiri** [comment]
Actually it only works in Firefox, but not in Chrome. That was unexpected.
FF 69.0b12
Chrome 76.0.3809.100

**Comment by surma** [comment]
Yes, I see that error, but I can click the increment button just fine in your demo.

The problem is that `unsubscribe()` returns an unsubscribe function and functions are not transferable, so that’s an error. It doesn’t stop the method call from working tho. If you want to rectify that, you can just discard functions that haven’t been wrapped with `Comlink.proxy()`. Here’s a patch:

<details>

```diff
diff --git a/src/remote-model/create-remote-store.js b/src/remote-model/create-remote-store.js
index 05b607e..df39b9a 100644
--- a/src/remote-model/create-remote-store.js
+++ b/src/remote-model/create-remote-store.js
@@ -1,5 +1,8 @@
-import { wrap } from "comlink";
+import { wrap, transferHandlers} from "comlink";
 import { remoteStoreWrapper } from "./remote-store-wrapper";
+import ignoreFunctionsTransferHandler from "./ignore-functions-transfer-handler";
+
+transferHandlers.set("IGNORE_FUNCTIONS", ignoreFunctionsTransferHandler);
 
 export const createRemoteStore = async () => {
   console.log("starting remote model worker ...");
diff --git a/src/remote-model/ignore-functions-transfer-handler.js b/src/remote-model/ignore-functions-transfer-handler.js
new file mode 100644
index 0000000..74af1a3
--- /dev/null
+++ b/src/remote-model/ignore-functions-transfer-handler.js
@@ -0,0 +1,5 @@
+export default {
+  canHandle: (v) => v instanceof Function,
+  serialize: (v) => [0, []],
+  deserialize: () => 0,
+};
diff --git a/src/remote-model/root-store.expose.js b/src/remote-model/root-store.expose.js
index 7a462f2..4acd8a7 100644
--- a/src/remote-model/root-store.expose.js
+++ b/src/remote-model/root-store.expose.js
@@ -1,4 +1,7 @@
-import { expose } from "comlink";
+import { expose, transferHandlers, transfer } from "comlink";
 import { store } from "../root/create-store";
+import ignoreFunctionsTransferHandler from "./ignore-functions-transfer-handler";
+
+transferHandlers.set("IGNORE_FUNCTIONS", ignoreFunctionsTransferHandler);
 
 expose(store);
```

</details>

Your async increment button doesn’t work for me because you are trying to send a promise. But I don’t quite understand what you are doing there so I wasn’t able to fix that. Hope this helps!

**Comment by sladiri** [comment]
Hello Surma, sorry for the late reply. Thank you very much for the detailed example. I think this is what you meant in your article with 

>  I did take some shortcuts here (like ignoring the return value of remoteStore.subscribe()), ...

That Promise is for notifying the caller when the action was processed, since I do that in a Saga (and use stateful Components). Anyway, I can keep the promise in the UI thread, so there is no need to send the Promise anymore.

**Comment by awwit** [comment]
@surma why not just add such a solution to your code?

(Made based on your proxy code: https://github.com/GoogleChromeLabs/comlink/blob/master/src/comlink.ts#L87-L98)

`proxy-functions-transfer-handler.ts`

```ts
import { expose, proxy, wrap, Remote } from 'comlink'

export default {
  canHandle(value: any): boolean {
    return typeof value === 'function'
  },

  serialize(value: Function): [MessagePort, Transferable[]] {
    const obj = proxy(value)

    const { port1, port2 } = new MessageChannel()

    expose(obj, port1)

    return [port2, [port2]]
  },

  deserialize(value: MessagePort): Remote<MessagePort> {
    value.start()

    return wrap<MessagePort>(value)
  },
}
```

I want to know what problems this solution may have?

**Comment by surma** [comment]
@awwit That is definitely possible but I definitely _won't_ ship that by default, I am even hesitant to adovcate for that pattern. It's mostly that "magically" supporting functions might leave a lot of code running on one thread when it was intended to run on _the other_ thread. Because of that I want the developer to explicitly opt-in for a function to be proxied.

But your solution is technically correct and works, so as long as you are aware of what's happening, feel free to use it :)

**Comment by awwit** [comment]
@surma Ok, I understand, thank you for the answer :)
