### ISSUE TITLE
Symbol properties not serialized

### ISSUE THREAD

**Issue by SebastianSpeitel** [GoogleChromeLabs/comlink#349]
I am using comlink to expose an instance of [idb](https://github.com/jakearchibald/idb) from a worker to the main thread.

To be exact, I am calling `comlink.expose()` with the Promise returned by `idb.openDB()` and 
`comlink.wrap()` with the usual worker constructor (`new Worker('path/to/worker.js')`).

Now printing the value returned by `wrap` throws an TypeError in the worker thread.
After a bit of debugging I found out, that printing (using `console.log`) calls `obj[Symbol.toPrimitve]`, which gets serialized to the path `["Symbol(Symbol.toPrimitive)"]` and because the key `Symbol(Symbol.toPrimitive)` doesn't exist on the object on the worker side and `.apply()` is called on it, it throws.

I am wondering if it has to do with the fact, that it's a promise wrapped by comlink and if not, why this problem didn't occur before, because every object returned by `wrap` should have this problem.

PS.:
Because of a bug in chrome devtools (https://bugs.chromium.org/p/chromium/issues/detail?id=995753) proxies, such as the one created by comlink are not regarded as side-effecty and so typing in the name of the returned proxy results in one error per keypress.

**Comment by surma** [comment]
Hm yeah, I haven’t had that issue before, not sure what is special about what you are doing there. I think the new version of idb uses proxies itself, so maybe that has something to do with it. Either way, Symbols can’t be serialized and are not transferable, so there’s nothing I can do here.

I could potentially add some special handling for well-known properties, but that wouldn’t add much as they are often expected to be synchronous.

**Comment by surma** [comment]
Would you mind putting a sample in a glitch or something? I’d like to take a closer look at some point :)

**Comment by SebastianSpeitel** [comment]
Here it is: https://iron-wisteria.glitch.me/

Never used glitch before, but being able to do this in under 5min was quite pleasent.

**Comment by surma** [comment]
Appreciate it! I’ll take a look soon :)

**Comment by SebastianSpeitel** [comment]
I just noticed the typing explicitly says symbols are allowed:
https://github.com/GoogleChromeLabs/comlink/blob/ba62f956ac6c9d305e8d39fddda58533d7b02499/src/comlink.ts#L163

**Comment by surma** [comment]
Yeah you can *proxy* a symbol. But you can’t transfer it.

**Comment by SebastianSpeitel** [comment]
If the structured clone algorithm is being able to clone something like this:

```js
const fakeSymbol = 'foo';
fakeSymbol.symbol = true;
```
we could send something like that via postMessage.

**Comment by surma** [comment]
That wouldn’t keep symbol properties in tact, tho. Let work with the well-known symbols.

**Comment by SebastianSpeitel** [comment]
Of course the traversal function would need to be changed.

From:
https://github.com/GoogleChromeLabs/comlink/blob/ba62f956ac6c9d305e8d39fddda58533d7b02499/src/comlink.ts#L111
To something like:
```js
const rawValue = path.reduce((obj, prop) =>
        prop.knownSymbol
        ? obj[Symbol[prop]]
        : obj[prop],
    obj); 

This would still result in async response, but at least it doesn't throw an error and is awaitable to the desired result.
