### ISSUE TITLE
Comlink function could not be cloned with electron/react

### ISSUE THREAD

**Issue by willium** [GoogleChromeLabs/comlink#360]
Behavior wise, everything is working as expected. However, we are getting a confusing error in the console
![Screen Shot 2019-09-12 at 11 48 14 AM](https://user-images.githubusercontent.com/356976/64812022-40f04200-d553-11e9-9b7b-7f829c7348f5.png)

The worker's code is quite straightforward:
```
import * as Comlink from "comlink"

export class Compiler implements ICompiler {}

Comlink.expose(Compiler)
```

The worker is being used as follows
```
const compiler: Promise<Comlink.Remote<Compiler>> = new (Comlink.wrap<typeof Compiler>(new CompilerWorker()))()
```
and again, **works** as expected, save for the weird errors.

Basically, even an empty class causes Comlink to throw about a function. We think it must be due to some environmental issues with react.dom/electron/chrome but it's unclear where to start looking based on the error message.

**Comment by rssfrncsrenishaw** [comment]
@willium i'm having similar issues did you solve this?

**Comment by willium** [comment]
@rssfrncsrenishaw yes, the issue for us was importing/requiring modules into the worker. Try changing all module resolution paths to direct paths.

**Comment by FilipeCosta06** [comment]
Awh gawd... Everything was working fine on my laptop. I just switched to another PC and now I have this same issue.

It is as you say, there are error messages yet everything works perfectly (relatively ahah)... And this is flooding the console in dev and production mode (and, in dev mode, this causes React's debug popup to display...).

Hell no, I'm not going to deal with this now! Back to laptop it is.

On a more serious note, I am not exactly sure what you mean by 
> Try changing all module resolution paths to direct paths.

I will do some googling but I am quite new to all this and still use the default (non-ejected) react-create-app config. If you meant "absolute paths" that'll be problematic in my case but oh well ^^
