### ISSUE TITLE
Limiting console logs

### ISSUE THREAD

**Issue by idanen** [GoogleChromeLabs/comlink#368]
First of all, thanks for this amazing package!

We use it to communicate between an iframe and its parent.
The iframe might have some more iframes that send their own messages (not wrapped for Comlink).
For each message Comlink spits out a warning to the console.

How about opting out of these messages?
Or maybe opt out by default and printing only if opting in?

**Comment by surma** [comment]
Yeah, I actually don't know why I have those still in there. I don't think an opt-out is actually preferable (it's even more code and most of the time you'd want to opt-out). I'll switch to a silent model.

**Comment by surma** [comment]
Published in v4.0.3!
