### ISSUE TITLE
Possible to know when remote interface initialised

### ISSUE THREAD

**Issue by git-jiby-me** [GoogleChromeLabs/comlink#37]
Would it be possible to know from a proxy, if the backing worker, or iframe is already up and will respond to your requests.

I have situation when i want wait until iframe is ready before i start calling remote api, ideally something like this
```
var remoteApi = await Comlink.proxy(iframe.contentWindow)
// now i am sure that iframe loaded and i can call the remote api's
```

Currently to do the same, i am forced to sent a postMessage from iframe when its loaded, and listen for this in main page, and then start using the remote api's using Comlink

**Comment by surma** [comment]
As long as you wait on the iframe’s `onload`, you are fine (you can build your own `ready()` or something to make it more semantically meaningful). Here’s a [glitch example](https://glitch.com/edit/#!/comlink-issue-37).

I can’t really bake that mechanism into Comlink as the mechanism differs for Workers, iFrames and what not. 

Does that help?

**Comment by git-jiby-me** [comment]
@surma that does help, but the idea was more of having a generic mechanism that works for all kinds of targets.

Is it not possible that
- when `proxy` is called, send a `load-check` message to the target
- when `expose` is called or when `load-check` message is received, send a `loaded` message to the target

Cannot such a mechanism, implement this in a generic way ?

**Comment by surma** [comment]
I don’t think there’s a generic *and* reliable way to make sure the channel is initialized — exactly because there’s no way to make sure the `load-check` message doesn’t get lost itself. You have to rely on the underlying channel semantics to make sure it’s ready.

Imma close this for now, but feel free to re-open if you think you have a good way!

**Comment by adrianromanko** [comment]
@surma In my case, a child iframe application is waiting to receive an API via getInstance()...the challenge I'm facing is that the react or angular child application in the child iframe has already finished rendering by the time the proxied instance is received. Hence, there is a large delay sending comlink.proxyValue(...) and the only way to guarantee that the proxied value exists prior is have a hook that mounts the iframe content after resolving ---> await api.Comunication.getInstance();

**Comment by surma** [comment]
I can’t quite follow. Neither `expose()` nor `proxyValue()` send anything. The just hook up to a message channel.

The process is inherently async, there’s nothing I can do about that. If you need to wait for the other side to be “ready” in some form, then that needs to be build on top of Comlink.

Can you maybe give me an example I can test with?

**Comment by adrianromanko** [comment]
I answered my own question. Thanks. Like you mentioned, it needs to be build on top of Comlink.
