### ISSUE TITLE
Built-in termination/cancellation?

### ISSUE THREAD

**Issue by rssfrncsrenishaw** [GoogleChromeLabs/comlink#372]
Hi,

I'm currently using comlink + worker-plugin to handle web workers in my application. I'm wondering whether it is possible to terminate the worker created with `wrap` or do you suggest a better way such as handling task creation/cancellation within the worker file itself?

**Comment by surma** [comment]
You can always "cancel" a worker with `worker.terminate()` or `self.close()` from inside the worker. I don't think Comlink needs to provide anything here. Or am I misunderstanding you?

**Comment by rssfrncsrenishaw** [comment]
Hey thanks for your response.

Whilst it works isn't `self.close` deprecated? 

I think it would still be useful to terminate externally so by `worker.terminate` do you mean something like,
```
const worker = wrap(new Worker("./expensive.worker.js", { type: "module" })); 
worker.terminate();
```
?

**Comment by surma** [comment]
No, in your example, `worker` is your proxy, not the worker itself.

This ought to do it:

```js
const worker = new Worker("./expensive.worker.js", { type: "module" });
const proxy = wrap(worker);
// ...
worker.terminate();
```

**Comment by rssfrncsrenishaw** [comment]
Ah of course!

Thank you 👍
