### ISSUE TITLE
How to send async message from wrapped class to parent?

### ISSUE THREAD

**Issue by peteringram0** [GoogleChromeLabs/comlink#381]
I am using a class within Comlink.wrap with i use to run a file upload to a remote server. I would like the worker thread to send progress messages back to the parent which you can normally do with postMessage. How is this possible when using comlink please?

**Comment by surma** [comment]
I'd use a normal callback. Take a look at the [callback example](https://github.com/GoogleChromeLabs/comlink/tree/master/docs/examples/02-callback-example)

**Comment by peteringram0** [comment]
im looking to send multiple progress messages e.g. 10, 20, 30 as fire and forget.

**Comment by surma** [comment]
Callbacks can do that :D

```js
// main.js
const api = Comlink.wrap(new Worker("./worker.js"));
api.uploadFile();
api.onProgress(Comlink.proxy(progress => {
	console.log(`Current progress: ${progress}%`);
}));
```

```js
// worker.js
let callback;
let progress = 0;
const api = {
  uploadFile() {
	setTimeout(function f() {
      progress += 10;
      if(callback) {
        callback(progress);
      }     
      if(progress < 100) {
        setTimeout(f, 1000);
      }
    }, 1000);
  },
  onProgress(cb) {
    callback = cb;
  }
}
```

**Comment by peteringram0** [comment]
Oh i see, thats a nice way of doing it!!! Thanks for the help @surma
