### ISSUE TITLE
Errors thrown in async methods are not forwarded correctly

### ISSUE THREAD

**Issue by etamponi** [GoogleChromeLabs/comlink#382]
To reproduce:

**main.js**
```javascript
import * as Comlink from "https://unpkg.com/comlink/dist/esm/comlink.mjs";
async function init() {
  const worker = new Worker("worker.js");
  const obj = Comlink.wrap(worker);
  try {
    await obj.throwError();
  } catch (err) {
    console.log("Error caught", err);
  }
}
init();
```

**worker.js**
```javascript
importScripts("https://unpkg.com/comlink/dist/umd/comlink.js");

const obj = {
  // THIS IS THE IMPORTANT BIT
  async throwError() {
    throw new Error("foo bar");
  }
};

Comlink.expose(obj);
```

If you remove `async` from `throwError`, the error is caught. Otherwise you get an `Uncaught (in promise)` error in the console.

**Comment by etamponi** [comment]
The issues lies at https://github.com/GoogleChromeLabs/comlink/blob/master/src/comlink.ts#L153. I've changed it to:

```typescript
    Promise.resolve(returnValue)
      .catch(err => {
        throwSet.add(err);
        return err;
      })
      .then(returnValue => {
```

and now it correctly catches errors thrown in async functions.

**Comment by surma** [comment]
Wanna open a PR that adds a test and this fix?

**Comment by etamponi** [comment]
Sure :) It might take a while because I'll be a bit busy for the next few days

**Comment by surma** [comment]
Same 😂 I probably can't get back to this until mid-November anyway :)

**Comment by hellboywar** [comment]
I also encountered this bug today while upgrading to latest comlink, but I can't wait that long, so I fixed it in [PR](https://github.com/GoogleChromeLabs/comlink/pull/384)

@surma thank you for the comlink - it's a delight to work with

P.S. hope you could publish fixed version sooner!
