### ISSUE TITLE
Module not found: Error: Can't resolve './protocol.js'

### ISSUE THREAD

**Issue by nevcos** [GoogleChromeLabs/comlink#398]
Getting the following error when building a project using webpack:
```Module not found: Error: Can't resolve './protocol.js' in '(...)/node_modules/comlink/src'```

This only happens when:
- Using [ts-loader](https://github.com/TypeStrong/ts-loader/) with `transpileOnly: true`
- Importing comlink source files directly like `import {wrap} from "comlink/src/comlink"`

The import fails because the file `protocol.js` doesn't exist, it should be `protocol.ts` (or just `protocol`). This affects all imports.

Versions:
- comlink@4.1.0
- webpack@4.29.0
- ts-loader@5.3.3

Will create a PR in next minutes.

**Comment by jo4santos** [comment]
:+1: !
