### ISSUE TITLE
Comlink for Long Running Workers?

### ISSUE THREAD

**Issue by torch2424** [GoogleChromeLabs/comlink#400]
Yo @surma ! I'm following up from our chat at CDS with some of the ideas / thoughts I had for Comllink 😄 

So just as a text explanation: what about especially performance-constrained applications? In this case, rather than chunking off one of commands, re-instantiating the worker every time, does it make more sense to one long-running worker? I know you suggested you could have a worker that uses callbacks to run a command and return a response everytime. But to give some context, in [WasmBoy I explicitly need to ensure the data is a transferrable](https://github.com/torch2424/wasmboy/blob/master/lib/wasmboy/worker/update.js#L241) or else the transfer will not be fast enough to achieve the performance gains from workerizing, or even hit 60fps in some cases, which I know from @JamesLMilner 's amazing [Web Worker Benchmark Article](https://www.loxodrome.io/page/2/). Thus I am not entirely sure if that is how the callback system works? 

Let me know what you think! 😄

**Comment by surma** [comment]
Hm, I'm not sure I follow. I always advocate for long-running workers, especially when Comlink is in use :D 

Regarding your callback + transferable question: That should work fine!

```js
// main.js
const api = Comlink.wrap(worker);
api.addStateChangeListener(Comlink.proxy(state => {
  // ...
}));
```

```js
// worker.js
const cbs = [];
Comlink.expose({
  addStateChangeListener(cb) {
    cbs.push(cb);
  }
});

// Transfer some ArrayBuffer every 16ms or something.
setInterval(() => {
  for(const cb of cbs) {
    const val = new Uint8Array([1,2,3]);
    cb(Comlink.transfer(val, [val.buffer]));
  }
}, 16);
```

Does that make sense/help?

**Comment by torch2424** [comment]
@surma 

> Hm, I'm not sure I follow. I always advocate for long-running workers, especially when Comlink is in use :D

Oh dude, please excuse me, for some reason when I incorrectly had this though, I though Comlink worked like [greenlet](https://github.com/developit/greenlet).  😂 It was like one of those thoughts you have while walking, and it's been in the back of my head, but yeah that totally is wrong my bad haha!

> Regarding your callback + transferable question: That should work fine!

Oh this is perfect! I really need to [read the docs](https://github.com/GoogleChromeLabs/comlink#comlinktransfervalue-transferables-and-comlinkproxyvalue) haha! 😂 

Please excuse this issue, and I went ahead and opened this [issue on WasmBoy](https://github.com/torch2424/wasmboy/issues/307), because I think it'd be a really cool use case for that 😄 

Thanks again!

**Comment by surma** [comment]
No worries! Let me know if you run into any DX issues :)
