### ISSUE TITLE
Request: Internet Explorer 11 with proxy-polyfill  example

### ISSUE THREAD

**Issue by sdykae** [GoogleChromeLabs/comlink#401]
from #389 I was thinking that is posible to use with Internet Explorer 11.
I've polyfilled proxy with proxy-polyfill and use core-js/stable + regenerator/runtime to solve  Symbol and others but still can't get comlink to work.

I tried https://github.com/sdyalor/comlink.pwa to deploy this way with webpack and worker-plugin
transpiling source, using old comlink version(with es5 dist), but no success ;'c

**Comment by ahnpnl** [comment]
I also run into an issue with IE11 that comlink is es6 while IE11 is not fully compatible with es6. I did try to compile to es5 but then I ran into other issues.

**Comment by zamber** [comment]
Same here. Stumbling on the ES6 issue.

I just noticed there's a browser support section and as IE goes there's only Edge there (listed in barely readable badges...).

**Comment by sdyalor** [comment]
I got comlink to work, there are restrictions with some bindings but proxy-polyfill needs the source object to be defined like the remote one cuz is sealed (just seals the outside properties)

**Comment by sdyalor** [comment]
https://github.com/sdyalor/comlink.pwa/blob/2e1a71a8c46e16c78e82b3f00219db0cfdbaae8b/src/index.js#L87 this should fix
PD: As maintainer advice, We should use the sourse code, then bundle it, then use, cuz release with proxy-polyfill is not released.

**Comment by scienfier** [comment]
got error: Uncaught TypeError: Cannot read property 'expose' of undefined; when using comlink it just said uncaught promise in IE 11 and expanded are symbol keys with a lot undefined. 

It is frustrating to think about IE 11

> https://github.com/sdyalor/comlink.pwa/blob/2e1a71a8c46e16c78e82b3f00219db0cfdbaae8b/src/index.js#L87 this should fix
> PD: As maintainer advice, We should use the sourse code, then bundle it, then use, cuz release with proxy-polyfill is not released.

**Comment by scienfier** [comment]
> https://github.com/sdyalor/comlink.pwa/blob/2e1a71a8c46e16c78e82b3f00219db0cfdbaae8b/src/index.js#L87 this should fix
> PD: As maintainer advice, We should use the sourse code, then bundle it, then use, cuz release with proxy-polyfill is not released.

confirmed working... I think It should be  import * as Comlink in your example code?  Maybe IE is outdated, still runs very slow with the help of web worker.

**Comment by surma** [comment]
Just wanted to go on record: I’m super happy that you folks are helping each outer out. Thanks to everyone who is participating.

I won’t add IE11 support to Comlink itself, it’s just too much maintenance and work and I don’t even have a way of properly testing. If you find a good solution, please document it here :)

**Comment by benjamind** [comment]
Given the end of life of IE11 last year I think we can close this out now.
