### ISSUE TITLE
Request: Add targetOrigin as optional parameter to windowEndpoint

### ISSUE THREAD

**Issue by barnawhi** [GoogleChromeLabs/comlink#404]
Adding this parameter would allow you to use the built in filtering Window.postMessage provides.  It seems if it were an optional parameter the function would remain backwards compatible (by continuing to fallback to '*' when unspecified).

**Comment by surma** [comment]
This is a good idea! Feel free to open a PR, otherwise I’ll tackle this when I next get around to it.

**Comment by surma** [comment]
Related: #395
