### ISSUE TITLE
Worker is undefined. Is there any Worker polyfill supported with comlink?

### ISSUE THREAD

**Issue by chuckWu1989** [GoogleChromeLabs/comlink#406]
Hi, folks.
I faced a problem that the worker is undefined. It's a well known issue in sub worker of chrome which version is less than 69 (issue here: https://stackoverflow.com/questions/33990712/uncaught-referenceerror-worker-is-not-defined-while-trying-to-create-a-worker-w/33991381). I had tried many polyfill solution I could find in websites. Such as:

https://github.com/dmihal/Subworkers

Received error

![image](https://user-images.githubusercontent.com/14174895/69611945-ca4ee500-1069-11ea-8c86-3554bba64c5e.png)

https://github.com/pmarfany/worker-polyfill

There is no response and the promise was never return.

https://github.com/nolanlawson/pseudo-worker

Failed. I had indexedDB in worker. This project used the fake worker so that the db failed.

Finally, I think Subworkers is a path we can keep going. However, I have no idea how to solve th problem. Help!

**Comment by benjamind** [comment]
Given this is only an issue in a very old and unsupported version of Chrome I think polyfilling workers is not a necessarything at this time. Though some browsers still don't supported nested sub workers I doubt there's any good path to polyfilling this reliably right now and we should see standardization on support for this capability. So closing as won't fix for now, feel free to re-open if this is still an issue for you.
