### ISSUE TITLE
Does comlink support string-based messaging?

### ISSUE THREAD

**Issue by kirbysayshi** [GoogleChromeLabs/comlink#430]
Hello!

I've been trying to get react-native and a react-native-webview communicating via comlink. I've tried the library mentioned in https://github.com/GoogleChromeLabs/comlink/issues/87, as well as some other non-comlink solutions too. The library in #87 seems out of date, and others cannot transfer instances or perform `new`...

react-native has a string-based messaging bridge in and out of a WKWebView. Specifically, from react-native you can do: `webView.injectJavaScript("console.log('hello'))`, and from the webview you can do: `window.ReactNativeWebView.postMessage("world. has to be a string")` (but note: that `postMessage` API accepts _one_ argument and it must be a string).

So that leaves the big question:

- does comlink support pure string-based communication, or does it absolutely need `Transferable` support (for message ports)?

**Comment by surma** [comment]
Ha, funny you should ask this. I just recently re-wrote that old adapter.

You can find an experimental version on the `string-channel` branch. Here is an example on how to use it: https://github.com/GoogleChromeLabs/comlink/tree/9161fa4109c787ea3834e98d41d05407f48ffc17/docs/examples/99-nonworker-examples/node-over-websocket

That being said, it’s more of a hack. I wouldn’t use it in production.

Hope that helps?

**Comment by kirbysayshi** [comment]
Wow very cool! Nice to know there is at least a hacky way. Thanks for sharing!

Feel free to close this issue, although having it open might help others if they end up looking for a string bridge.

Thanks again!
