### ISSUE TITLE
TypeScript types incompleteness

### ISSUE THREAD

**Issue by felixfbecker** [GoogleChromeLabs/comlink#432]
So after having depended on the fork from https://github.com/GoogleChromeLabs/comlink/pull/223 for a long time, I wanted to finally take on upgrading to v4. Unfortunately, I noticed that some of the finer details of the types in that PR did not make it into v4. Listing out below, please bear with me 🙌 

- `Promisify<T>` needs to check first whether `T extends Promise` already. Otherwise it could resolve to `Promise<Promise<T>>` if `T` already is a Promise  (which is impossible in comlink and JavaScript in general).

- In the mapped types, each right side generally needs to be extracted into its own type alias. This is because generic type aliases will distribute over union types, while inlining the type would not. This means the type would not work properly when union types are involved. This may sound like an edge case, but includes e.g. optional properties, which are union types `xxx | undefined`.

- For proxied functions, while the return type needs to be wrapped in `Remote<T>`, the parameters of the functions need to have the _inverse_ applied. This is because from the point of view of the function implementation, passed callbacks will now return Promises, and therefor they need to type their signature accordingly. But the caller does not actually need to provide a callback that returns a Promise, from the point of view of the caller it just needs to pass a synchronous callback.
  - This means the library needs to define symmetric, recursive types for "remotification" and "deremotification". Within either, parameters get treated with the inverse transformation respectively, recursively.

This is quite hard to explain and took me quite some time to understand myself. I did my best to explain this at the TS Seattle meetup, which may be a better way to  explain: https://youtu.be/sSkx5SVc2OA?t=732

**Comment by johnnyreilly** [comment]
> Promisify<T> needs to check first whether T extends Promise already. Otherwise it could resolve to Promise<Promise<T>> if T already is a Promise (which is impossible in comlink and JavaScript in general).

I noticed this when I was writing with v4. I was initially worried, but consumption seemed to be unproblematic. `await`ing `Promise<Promise<T>>` still yielded `T`. 

Did you have a different experience?

**Comment by trusktr** [comment]
The nested promises do indeed unfold. Try in this in console:

```js
async function test() {
  const st = setTimeout
  const p = new Promise(r1 => st(() => {
    r1(new Promise(r2 => st(() => {
      r2(new Promise(r3 => r3('42')))
    })))
  }))

  console.log(await p)
}

test()
```

**Comment by trusktr** [comment]
Can methods on a worker side `class` can be `async`?

**Comment by felixfbecker** [comment]
It unfolds if you `await`, yes. But if you try to pass the type into any other generic type, things will go wrong. As a simple example, if you try to convert the Promise to an Observable with `rxjs` `from()`, which converts `Promise<T>` -> `Observable<T>`, but this will result in `Observable<Promise<T>>`, which is not what the type actually is so the type of the value will be wrong inside `subscribe()`.

**Comment by felixfbecker** [comment]
Fixed with #452 :)

**Comment by fourteenmeister** [comment]
The same thing in version 4, in version 3 everything works

**Comment by felixfbecker** [comment]
@fourteenmeister this issue was reported (by me) _about_ v3 and was fixed (by me) in v4, so you must be experiencing a different issue. Could you open a new issue and describe what exactly is not working?

**Comment by fourteenmeister** [comment]
> @fourteenmeister this issue was reported (by me) _about_ v3 and was fixed (by me) in v4, so you must be experiencing a different issue. Could you open a new issue and describe what exactly is not working?

Already, #481
