### ISSUE TITLE
Migration from MessageChannelAdapter?

### ISSUE THREAD

**Issue by felixfbecker** [GoogleChromeLabs/comlink#433]
In v3, we used `MessageChannelAdapter` to wrap Chrome `Port`s used in the Chrome extension API. Is there an equivalent for v4?

**Comment by surma** [comment]
Ha, this is the same question as #430 

Fwiw, in retrospect I shouldn’t have put `MessageChannelAdapter` on master in v3. It was a hack more than anything else. For v4 I have something in the `string-channel` branch that is similar, slightly better but still hacky. Take a look!

Once I have more time to productionize it, I might pull it into master. Hope that helps.
