### ISSUE TITLE
Question: Does it work with node child processes ?

### ISSUE THREAD

**Issue by jd1378** [GoogleChromeLabs/comlink#441]
Hi
Does it work with [node child process](https://nodejs.org/api/child_process.html) ?

**Comment by surma** [comment]
It does work with [Node workers](https://nodejs.org/api/worker_threads.html).

See the [example](https://github.com/GoogleChromeLabs/comlink/tree/968768ac9df3aca6fe4d1049185d2605a70544cc/docs/examples/06-node-example).

**Comment by jd1378** [comment]
thanks, but I already know that it works with node workers from the docs, wanted to know if it works with node child process,
since I think node workers performance will start to degrade when there's too many of them, and I can't use thread pool because of relying on a third party package (you can think of chat bots), so I need to use child process

**Comment by surma** [comment]
> since I think node workers performance will start to degrade when there's too many of them

What makes you think that? `worker_threads` is just a very thin layer on top of `child_process`, giving you a `postMessage()` interface.

> I can't use thread pool 

You can use a worker pool.

Comlink can’t work directly with `child_process` because it doesn’t have `postMessage()` or any other means of communicating. But `worker_threads` is just a simple abstraction of `child_process` and should be compatible with whatever you want to do.

**Comment by jd1378** [comment]
Thanks for the reply,
I understand that it can't work with child_process normally, but it can if it's spawned using `fork` method, It would just need another node-adapter i guess

but how worker_threads can be a thin layer on top of child_process when child_process spawns a new process and worker_threads does not ?
Can you provide a bit of info If you don't mind ? I did some search but couldn't find info on this, took a quick look at node's [`worker_threads`](https://github.com/nodejs/node/blob/master/lib/worker_threads.js) and [`child_process`](https://github.com/nodejs/node/blob/master/lib/child_process.js) and it looks like they work *very* differently and do not depend on each other
I appreciate if you explain

**Comment by surma** [comment]
Oooh, I have _never_ noticed `send()`. Apologies for not seeing that!

Looking at `send()`, it misses transferable `MessagePort`, which `postMessage()` supports and are crucial for how Comlink works.

I have a _super_ hacky implementation for string-based communications in a branch which you can give a try. It’s not very well tested, but I wrote it to make Comlink work with WebSockets. Take a look at #430.

**Comment by jd1378** [comment]
I understand there's limits on what can be sent over string-based communications (only simple values and objects)
Other than that , is there any other reason that it shouldn't be used in production ?
also is there any eta on this feature ?

**Comment by surma** [comment]
The main problem is that on the receiving end of a `MessagePort`, I don’t know which values were being transferred. I have an [open issue on the HTML spec](https://github.com/whatwg/html/issues/4521) for that. Until that is fixed and implemented in browsers, this hack is most likely leaky and has bad performance. So no ETA on this ever making it to master for now. However, feel free to rip it out and use it, if it fixes your problem.
