### ISSUE TITLE
Start time must be strictly greater than previous start time

### ISSUE THREAD

**Issue by giacomorebonato** [GoogleChromeLabs/comlink#447]
Hi, I see this error only on Safari IOS and I don't understand what it means:

<img width="1075" alt="Screenshot 2020-04-11 at 18 48 17" src="https://user-images.githubusercontent.com/630796/79050914-0eabdd80-7c25-11ea-9033-f7a9e9691ff4.png">

This is [the code ](https://github.com/giacomorebonato/mino-timer/blob/master/src/createStore.ts#L54).
The app is [deployed here](https://mino-timer.now.sh).
If you create a timer then it will throw an error when you start it, not immediately but when it's moving to the next timer.

The timer is a `setInterval` that is running inside of a worker.

**Comment by giacomorebonato** [comment]
The error is coming from the proxy function.

**Comment by giacomorebonato** [comment]
The problem was somewhere else... solved.

**Comment by dalvan-bevilaqua** [comment]
hay, I am using the code abose. I have the problem..
Uncaught (in promise) DOMException: Unable to decode audio data
