### ISSUE TITLE
Question: Return multiple Transfer objects from one function?

### ISSUE THREAD

**Issue by jfuehner** [GoogleChromeLabs/comlink#461]
@surma was curious if there is a way to return multiple `Comlink.Transfer` objects from one function? I have a worker that has a number of transfer objects and presently I am doing a Promise.all to retrieve them from the worker...

const [fillColors, lineColors, lineWidths, positions] = await Promise.all([
 worker.fillColors, workier.lineColors, worker.lineWidths, worker.positions
]);

```
Class Worker {
    constructor(id) {
        this._id = id;
    }

   async fillColors() {
      return Comlink.transfer(fillColors, [fillColors.buffer]);
   }

  ... other functions ...
}
```

Wondering if there is a more efficient way to get all the transfer objects in one go?

**Comment by surma** [comment]
You could have a function that returns them all, like this:

```js
class Worker {
  // ....
  async getTheImportantStuff() {
      return Comlink.transfer([fillColors, lineColors, lineWidths], [fillColors, lineColors, lineWidths]);
  }
}
```

Does this help?

**Comment by jfuehner** [comment]
@surma that's awesome! I didn't realize the `transfer` function could take in arrays. Safe to assume that would be more performant than calling each function independently?

**Comment by surma** [comment]
Yes, probably more performant as it’s just a single round trip.

The first parameter to `transfer()` is just your return value of the function, it can be anything, really. The second parameter is the transfer list, just like [`postMessage()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage). 

I’ll close this, then :) Feel free to reopen if there are more issues.
