### ISSUE TITLE
Error when trying to use input FileList Files

### ISSUE THREAD

**Issue by ghostandthemachine** [GoogleChromeLabs/comlink#473]
While trying to use comlink for file uploading I am getting the below error. I've tried converting the files to blobs and get the same error. 

`Uncaught (in promise) TypeError: Cannot assign to read only property 'name' of object '#<File>'`

I would guess others have tried this before so quite possible it's on my end. Would be great to confirm this should work though if that is the case.

Awesome library!

**Comment by surma** [comment]
Can you write a minimal reproduction case and put it in a gist?

**Comment by ghostandthemachine** [comment]
Thanks for the quick reply. Did some more digging in and turns out this was an issue coming from Immer.js passing data, via comlink, from the worker back to UI thread. 

Sorry for the mix up.
