### ISSUE TITLE
expose/wrap with iframe on both sides

### ISSUE THREAD

**Issue by MrMadClown** [GoogleChromeLabs/comlink#474]
I am using this library to communicate between an Iframe and its parent window.
Both provide an API through `expose` and `wrap` each other.

Now sometimes i run into the Exception `TypeError: rawValue is not a constructor at callback`.

In https://github.com/GoogleChromeLabs/comlink/blob/master/src/comlink.ts#L317
I get a Message wich was supposed to be for the other side (serialized with a transferHandler)
And now comlink is trying to construct my exposed object,
because https://github.com/GoogleChromeLabs/comlink/blob/master/src/protocol.ts#L44 
and https://github.com/GoogleChromeLabs/comlink/blob/master/src/protocol.ts#L68 
both get compiled into `3`.
Afterwards its playing ping pong with following the following MessageData:
`"{"type":3,"name":"throw","value":{"isError":true,"message":"rawValue is not a constructor","stack":...}"`

I'll provide a minimal example of my setup. I'm sure this is not a bug but rather a Problem with my setup, but I currently don't understand how I could get the 2 way communication working otherwise.

**Comment by MrMadClown** [comment]
https://github.com/MrMadClown/comlink-iframe-2-way-example

**Comment by MrMadClown** [comment]
I think this could be solved by switching the `MessageTypes/WireValueType` enums to strings which do not overlap, and then add a default case to `expose` which just returns?

**Comment by chris-kruining** [comment]
I'm not fully sure on this one, but calling `Comlink.proxy` could be you solution

as in 
```
Comlink.expose(new Proxy(new Service()), self);
```

would become 
```
Comlink.expose(Comlink.proxy(new Proxy(new Service())), self);
```

this suggestion is likely to be wrong, but maybe worth a shot

**Comment by chris-kruining** [comment]
I also work with a page-iframe set up, and I think I spotted your isssue. this is my code

"index.html"
```
const self = this;
        const state = Comlink.proxy(this.#state);
        Comlink.expose(
            class
            {
                static async token()
                {
                    return self.token;
                }

                static onAction(callback)
                {
                    self.#page.on({ action: details => callback(details) });
                }

                static get apps()
                {
                    return Array.from(self.navigationItems, v => v.value);
                }

                static get state()
                {
                    return state;
                }

                static set route(route)
                {
                    self.goTo(route);
                }

                static set commands(commands)
                {
                    self.commands = commands;
                }
            },
            Comlink.windowEndpoint(this.#page.contentWindow, globalThis, app)
        );
```

"iframe.html"
```
const shell = Comlink.wrap(Comlink.windowEndpoint(globalThis.parent, globalThis))
```

based on a comparison with my code, I'd think that your `expose` needs a `Comlink.windowEndpoint` instead of self.

Again, I might very well be wrong.

**Comment by MrMadClown** [comment]
Getting back to this Issue,
@chris-kruining I tried the `proxy` method but It did not solve the Problem.
@surma is there anything wrong with the switch to the string enums?

**Comment by chris-kruining** [comment]
did you also try `Comlink.windowEndpoint` in `Comlink.expose`?

**Comment by MrMadClown** [comment]
Yes I did, it all seemed to work. But the Exception ping pong in the Background was still there.

**Comment by chris-kruining** [comment]
Aah I see, maybe this could be solved by introducing a channel concept to comlink? kind of like how topics in mqtt work?

**Comment by MrMadClown** [comment]
I'm not familiar with mqtt, Having "channels" sounds nice, but I think for a minimalistic library like this one, simply distinguishing between inbound and outbound messages seems more fitting. 
The channel concept could fit in a separate library using comlink under the hood?

**Comment by chris-kruining** [comment]
by that logic you could also implement this inbound/outbound distinction in your code, correct?

**Comment by MrMadClown** [comment]
Well no, since it involves changing the values of the `MessageTypes/WireValueType` enums. And I don't think I can do that from outside the library..
