### ISSUE TITLE
Performance issues with proxied function calls with heavy objects as arguments.

### ISSUE THREAD

**Issue by yelnar** [GoogleChromeLabs/comlink#478]
I used suggestions from [Surma's article](https://surma.dev/things/react-redux-comlink) and created a redux-like store in the worker. Although I am getting very poor performance.

A bit about my application: The store itself is quite big. Also, there is a WebSocket connection made within the same worker and it is subscribed to continuous events. For the sake of performance, I am batching those events so every 500ms I will update the store. Later I noticed that even if I do not use any data from the worker store my UI is still laggy. Finally, I found out that the cause for this issue is a dispatch function inside `createStore`:
```
const dispatch = (action: Action) => {
  const newState = reducer(state, action);
  subscribers.forEach((fn) => fn(newState));
};
```

So once I changed it to:
```diff
const dispatch = (action: Action) => {
  const newState = reducer(state, action);
-  subscribers.forEach((fn) => fn(newState));
+  subscribers.forEach((fn) => fn({}));
};
```
Magic! It became very responsive.

Please notice that in both cases I was not doing anything with the `newState` inside `remoteStoreWrapper `:
```
const remoteStoreWrapper = async (
  remoteStore: Store<WorkerStoreState, WorkerStoreAction>
) => {
  ...
  workerStore.subscribe(
    proxy(() => {
      // do nothing.
    })
  );
  ...
};
```

So I think that the reason for my issue is because every time I call subscriber function with huge `newState`, UI thread copies that state object and it requires some work.

I am not sure if I have a solution for it, but if anyone has any idea, I would love to hear that.

**Comment by yelnar** [comment]
For whoever it might be interesting :)

Firstly, I started looking into other ways of sending data. Transferable objects caught my attention. Unfortunately, it is not useful in my case since I need to pass plain JS object, not an array buffer.

Then I realized that sending the whole state object does not make sense. I can send only the differences in the state. So I wondered if I should create my own tool for calculating and applying differences, or if there is already a library. And of course, there is one! And I have been using it already. It is called [immer](https://github.com/immerjs/immer).

And the funny thing is Surma already had an article explaining my issue: https://surma.dev/things/is-postmessage-slow.

**Comment by surma** [comment]
Ha I’m glad you found that blog post! I would have suggest patching, with Immer being a library that provides good patching :)

Another variant if you ever wanna go down the `ArrayBuffer` route would be my [buffer-backed-object](https://github.com/GoogleChromeLabs/buffer-backed-object) library that lets you use normal objects that are backed by an `ArrayBuffer`.

**Comment by yelnar** [comment]
Thank you, I will try it :)
