### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by fourteenmeister** [GoogleChromeLabs/comlink#481]
When create instance with comlink, i get an error (the same as in #423):
This expression is not constructable. Type 'Remote<unknown>' has no construct signatures

All worked in 3 version, but in 4 - not worked

**Comment by surma** [comment]
Can you please provide a test case that does not compile?

**Comment by fourteenmeister** [comment]
https://codesandbox.io/s/long-currying-t1c1n?file=/src/index.ts

**Comment by felixfbecker** [comment]
You are not passing a type parameter to `comlink.wrap()`, so comlink has no way to know what the shape of the remote object is, therefor it is `unknown` (and `unknown` has no construct signature).
It works if you pass a type parameter to `comlink.wrap()`: https://codesandbox.io/s/dreamy-cohen-lddlm?file=/src/index.ts

```ts
import * as ComLink from "comlink";
import type { FooService } from "./foo-service";

const RemoteFooService = ComLink.wrap<typeof FooService>(new Worker("/src/foo-worker.js"));

const run = async () => {
  const d = document.createElement("div");
  document.body.appendChild(d);
  d.innerText = "before";
  const worker = await new RemoteFooService(); // << works now
  d.innerText = "after";
  const promise = await worker.bar();
  const output = await promise;
  document.querySelector<HTMLElement>("#msg").innerText = output.join(", ");
};

run();
```

**Comment by fourteenmeister** [comment]
Cool! Thanks!
