### ISSUE TITLE
Can I pass dynamic worker path to create worker?

### ISSUE THREAD

**Issue by rakshabhartiya** [GoogleChromeLabs/comlink#482]
Suppose I have a service that creates worker proxy using comlink's wrap, when worker object is passed to it from different module, then how can I also pass the class name of Worker to service for the proxy to be created?

**Comment by rakshabhartiya** [comment]
Example: 
async function createMarkdownWorker<T extends object>(worker: Worker) {
  const workerProxy = wrap<typeof Markdown>(worker);
  return await new workerProxy();
}

Instead of Markdown classname, how can I pass the classname to createMarkdownWorker and use it in wrap?

**Comment by surma** [comment]
I don’t quite follow. The title suggest that this is about paths, but the example you provide is already using a `Worker` instance. If you want to expose multiple classes from the same worker, maybe this is helpful?

```js
// worker.js
import {expose} from "comlink";

class A {}
class B {}
class C {}
expose({A, B, C});
```

```js
// main.js
import {wrap} from "comlink";

const worker = new Worker("./worker.js");
const {A, B, C} = wrap(worker);

const a = await new A();
// ...
```

**Comment by rakshabhartiya** [comment]
If I do above, I get 'expression is not constructable'. How to make it constructable is my ask.

**Comment by surma** [comment]
Can you give me a full code sample on glitch or something?

**Comment by surma** [comment]
This is not a full reproduction case. Can you please create a gist or something with the full setup?

**Comment by rakshabhartiya** [comment]
const worker = new Worker("./worker.js");
Here, Is there any way I can pass a dynamic path of worker to Worker class?

**Comment by surma** [comment]
What you are talking about is a TypeScript issue, not really a Comlink issue. If you maintain a map from Worker file to type, you can achieve this as follows:

```ts
class A { }
class B { }
interface WorkerTypeMap {
    "./a.js": A,
    "./b.js": B
}

function createWorkerProxy(path: keyof WorkerTypeMap) {
    const worker = new Worker(path);
    return wrap<WorkerTypeMap[typeof path]>(worker);
}
```
