### ISSUE TITLE
Support for SharedWorker?

### ISSUE THREAD

**Issue by planty** [GoogleChromeLabs/comlink#485]
Hi, I want to use SharedWorker to share a worker between tabs? Is this supported?

**Comment by surma** [comment]
Yes, anything that has `postMessage()`, will work.

**Comment by planty** [comment]
Thanks for the confirmation - I just realised my question would have been better suited in the comlink-loader. It looks like that does not support SharedWorker?

**Comment by rakshabhartiya-gep** [comment]
Well, I get below error when I try to wrap a SharedWorker object.
"Argument of type SharedWorker is not assignable to parameter of type Endpoint.
Property postMessage is missing in type SharedWorker but required in Endpoint."

**Comment by surma** [comment]
That’s because you need to use `sharedWorker.port`

**Comment by tezf** [comment]
Hi surma, sorry to necro but I tried it out with a basic example from your repo with the worker swapped out for a SharedWorker. It doesn't work in the way I expected it would (sits there awaiting the promise forever), while the worker example works as expected. 

main
`  async function init() {
    const worker = new SharedWorker("worker.js");
    // WebWorkers use `postMessage` and therefore work with Comlink.
    const obj = Comlink.wrap(worker.port);
    alert(`Counter: ${await obj.counter}`);
    await obj.inc();
    alert(`Counter: ${await obj.counter}`);
  }
  init();`

worker.js 
`importScripts("https://unpkg.com/comlink/dist/umd/comlink.js");
// importScripts("../../../dist/umd/comlink.js");

const obj = {
  counter: 0,
  inc() {
    this.counter++;
  },
};

Comlink.expose(obj);
`

Is there something obvious I'm missing here?

**Comment by surma** [comment]
Huh, that is surprising. Let me re-open this and write a test for it.

**Comment by safareli** [comment]
Any updates on this? do you know where the issue can be?

**Comment by phyllisstein** [comment]
I created a somewhat naïve failing test: https://github.com/phyllisstein/comlink/commit/1fbee50859375605b65fe264141d8155a8631028. Haven't found time to dig into troubleshooting yet.

**Comment by phyllisstein** [comment]
A cursory glance at the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker) suggests there may be a missing step on the Worker side. The `connect` listener is meant to grab a `port` from its `event` and call `MessagePort#start`. Here's their example:

```js
onconnect = function(e) {
  var port = e.ports[0];

  port.addEventListener('message', function(e) {
    var workerResult = 'Result: ' + (e.data[0] * e.data[1]);
    port.postMessage(workerResult);
  });

  port.start(); // Required when using addEventListener. Otherwise called implicitly by onmessage setter.
}
```

Gonna dig into this tonight, unless someone more familiar with the codebase beats me to it. 😬

**Comment by surma** [comment]
@phyllisstein That’s a great start. Thanks for looking into this. If you find a good solution, please do open a PR :)

**Comment by serg-io** [comment]
Here's how I got it to work.

First, as @surma pointed it out, you have to use [`SharedWorker.port`](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker/port) when calling `Comlink.wrap`.

**main.js**

```javascript
import * as Comlink from "https://unpkg.com/comlink/dist/esm/comlink.mjs";
async function init() {
  const worker = new Worker("worker.js");
  // WebWorkers use `postMessage` and therefore work with Comlink.
  const obj = Comlink.wrap(worker.port);
  alert(`Counter: ${await obj.counter}`);
  await obj.inc();
  alert(`Counter: ${await obj.counter}`);
}
init();
```

Then, inside the worker, you have to call `Comlink.expose` within the [`onconnect`](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorkerGlobalScope/onconnect) callback so you can access the shared worker port.

**worker.js**

```javascript
importScripts("https://unpkg.com/comlink/dist/umd/comlink.js");

const obj = {
  counter: 0,
  inc() {
    this.counter++;
  },
};

onconnect = function(event) {
  const port = event.ports[0];

  Comlink.expose(obj, port);
};
```

Alternatively, you can do it in a single line:

```javascript
onconnect = (e) => Comlink.expose(obj, e.ports[0]);
```

I hope this helps.

**Pro tip:** You can access DevTools for any shared worker currently running in Chrome by going to: **chrome://inspect/#workers**

**Comment by bangonkali** [comment]
It would be nice if this great sample is also on the readme as it's really relevant use case.

**Comment by surma** [comment]
I agree with @bangonkali, this is a great sample.

@serg-io I never saw this. Sorry for never replying to this. Great work! Do you wanna open a PR and add this to the `examples` folder?

**Comment by serg-io** [comment]
Absolutely! I'll create a PR. ;)
