### ISSUE TITLE
Is it possible to reduce communication delay through [SharedArrayBuffer]

### ISSUE THREAD

**Issue by qq974969638** [GoogleChromeLabs/comlink#489]
Sorry, I don’t speak English, this question uses Google Translate, please understand whether the reading remains the same

Sorry, I don't know whether it is appropriate and correct to ask this question here, the following question is my assumption.

https://dassur.ma/things/is-postmessage-slow/
https://github.com/Bnaya/objectbuffer

Hello, I have read this article "https://dassur.ma/things/is-postmessage-slow/" carefully. I want to know whether <comlink> can cooperate with the <objectbuffer> project, assuming that <comlink> and <objectbuffer> work closely together, can it improve <Web Workers>.
My expectation is that the performance of <Web Workers> and <NODE.JS worker_threads> can be greatly improved and changed through the close cooperation between <comlink> and <objectbuffer>.

**Comment by surma** [comment]
If you use SABs, you should indeed look at objectbuffer or something like my [buffer-backed-object](http://github.com/GoogleChromeLabs/buffer-backed-object).
