### ISSUE TITLE
Won't start up in Electron

### ISSUE THREAD

**Issue by mikehall314** [GoogleChromeLabs/comlink#49]
Using Comlink within Electron causes Electron to crash, as Electron's Node-based background process doesn't have a `MessagePort` object.  Comlink is referring to the `MessagePort` global when enumerating the transferrable types.

If we can find some other way to test for MessagePort objects which doesn't assume the `MessagePort` global exists, then Comlink could be used to communicate between Electron's background and renderer processes.

**Comment by surma** [comment]
Yes, see #32 😃 

I am wondering if I should just bite the bullet and do a proper implementation for github.com/tmpvar/jsdom

**Comment by lneir** [comment]
might try this: https://github.com/mikehall314/electron-comlink
