### ISSUE TITLE
Calling `Worker()` rather than `Worker.default()`

### ISSUE THREAD

**Issue by fabiospampinato** [GoogleChromeLabs/comlink#495]
So I've got comlink configured with comlink-loader in my project, the issue is that no matter what I do comlink is not instantiating the worker properly, for some reason in my project it should call `Worker.default` but instead it calls `Worker`, which is not a function, which causes a crash in my project.

![image](https://user-images.githubusercontent.com/1812093/93140432-581fbd80-f6da-11ea-8aa8-7e310375f64b.png)

Maybe that's because I have TypeScript configured in a way that comlink doesn't like, nonetheless I think it should be able to instantiate web workers properly under this scenario too.

Could somebody take a look at this?

**Comment by fabiospampinato** [comment]
Patching the library to fetch `.default` first leads to this other error:

![image](https://user-images.githubusercontent.com/1812093/93142626-4dffbe00-f6de-11ea-98f1-e578d58b0fda.png)

**Comment by surma** [comment]
What makes you say that it _should_ be `Worker.default`? I have never seen than. It should really be `new Worker()`, not just `Worker()`. Do you have some kind of polyfill in place?

**Comment by fabiospampinato** [comment]
> What makes you say that it _should_ be `Worker.default`?

I'm not sure about it, but I said that mainly because `new Worker ()` throws an error and `new Worker.default ()` gives me a Worker instance, which I guess is what `new Worker ()` was supposed to do.

> Do you have some kind of polyfill in place?

Not really, I've just got TypeScript configured like so:

<details>
  <summary>tsconfig.json</summary>

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": true,
    "baseUrl": "src",
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "inlineSourceMap": false,
    "jsx": "react",
    "lib": ["dom", "es2015", "es2016", "es2017", "es2018", "es2019", "es2020", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "newLine": "LF",
    "noEmitOnError": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": false,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "resolveJsonModule": true,
    "sourceMap": false,
    "skipLibCheck": true,
    "strict": false,
    "strictBindCallApply": true,
    "strictFunctionTypes": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "suppressImplicitAnyIndexErrors": true,
    "target": "es2019"
  }
}
```

</details>


And the whole thing is running inside Electron v9.3.0, but I don't think I've misconfigured it to mess up web workers 🤔

**Comment by fabiospampinato** [comment]
For added context configuring `workerize-loader` seems to work as expected, but that doesn't have `comlink-loader`'s sweet singleton mode so I'd really like to try to get comlink to work.

**Comment by surma** [comment]
Can you put a _small_ reproduction project in a gist or something? This is very mysterious.

**Comment by fabiospampinato** [comment]
I'll try to craft a small repo that reproduces the problem, it make take a while though, I'll ping you back once it's done.

**Comment by fabiospampinato** [comment]
@surma Sorry I haven't had the time to make a minimal repo that reproduces the issue, I ended up just using `workerize-loader` and wrapping all the calls to functions in workers with a bit of code that handles instantiating the worker etc.

It'd be great if this got fixed and I could clean up my code a little bit but right now the current workaround works well enough for me to not be worth looking more into this issue.

Feel free to close this issue .
