### ISSUE TITLE
speed between web worker and main thread?

### ISSUE THREAD

**Issue by cchanxzy** [GoogleChromeLabs/comlink#504]
Hi,

Firstly, thanks for this great tool! It's brilliant.

Anyway, I wanted set up a demo using comlink-loader and create react app: https://github.com/cchanxzy/tutorial-create-react-app-with-web-worker-and-typescript 

As I was doing this, I noticed that the web worker processing took a lot longer compared to the main thread. I added some performance debug in the console log: https://cchanxzy.github.io/tutorial-create-react-app-with-web-worker-and-typescript/

I was wondering, am I doing something wrong?

**Comment by surma** [comment]
You are not measuring processing time but also message transfer time for the worker. You are sending an array of strings with one million elements. That is bound to take a couple of milliseconds. So this has nothing to do with comlink, but is as expected. If you wanna know more, I have [a blog post on the performance of postMessage](https://surma.dev/things/is-postmessage-slow/).

However, keep in mind that it might still be a good idea to move work to the worker, even if end-to-end time increases. If I run your example on a low-end phone and use the main thread version, the main thread is blocked for a second or two. With the worker variant, it stays responsive. Also for long arrays it might be beneficial to use array buffers and a library like [buffer-backed-objects](https://github.com/GoogleChromeLabs/buffer-backed-object).

**Comment by cchanxzy** [comment]
Thanks for the quick response!

Yes, I was thinking it was probably more to do with the message size than the actual processing.

I was trying to create an example to hang the UI, and I thought creating a massive array iteratively would do it. In retrospective, that's probably not the best demonstration because of the size of the message.

The blog post you linked was very insightful. Thank you.
