### ISSUE TITLE
Can't figure out a way to send data from worker to website

### ISSUE THREAD

**Issue by xeoneux** [GoogleChromeLabs/comlink#506]
All the examples show a way to invoke a method in the worker and then await the result. However, I'm trying to set up a scenario where I consistently send data from the web worker to be consumed by the website. I used postMessage and onmessage to send and receive data. How do I use comlink to do that? There's no example in the readme.

**Comment by surma** [comment]
You could use a callback, for example.

You can also just use Comlink “the other way around”, Comlink doesn’t care :D

**Comment by d1manson** [comment]
i'm trying to do it "the other way around", but not quite sure how.

**main.js**
```javascript
import * as Comlink from "https://unpkg.com/comlink/dist/esm/comlink.mjs";
async function init() {
  const worker = new Worker("worker.js");

  // this isn't right - it throws an error about trying to clone the object
  Comlink.expose({
     methodOnMainThead(m){
         alert(m)
    }
  }, worker);

  const obj = Comlink.wrap(worker); // as per the docs
}
init();
```

**worker.js**
```javascript
Comlink.expose({...}); // as per the docs

// don't think this is right either
const main = Comlink.wrap(self); 
...
await main.methodOnMain(42);
```

Thanks!

**Comment by surma** [comment]
Apart from a bunch of typos, you are mixing the two approaches, rather than sticking to one. That’s probably why you are seeing an error. So the parts where you say “don’t think this is right” are actually right :D You just can’t mix the normal approach (exposing worker to main thread) with your approach (exposing main thread to worker).

Here’s your example but with the extraneous lines removed so it works:

```js
// main.js
import * as Comlink from "https://unpkg.com/comlink/dist/esm/comlink.mjs";

async function init() {
  const worker = new Worker("worker.js", {type: "module"});

  Comlink.expose({
     methodOnMainThread(m){
         alert(m)
    }
  }, worker);
}
init();
```

```js
// worker.js
import * as Comlink from "https://unpkg.com/comlink/dist/esm/comlink.mjs";

async function init() {
  const main = Comlink.wrap(self); 
  await main.methodOnMainThread(42);
}
init();
```

**Comment by d1manson** [comment]
I see, that's a shame.
I think I will use the callback approach then. Perhaps something like:



```javascript
// main.js
...
const obj = Comlink.wrap(worker); // as per the docs
obj.exposeMain(Comlink.proxy({
  somethingOnMainThrea(){..},
  somethingElseOnMainThread(){...}
})
```

```javascript
// worker.js
let main;

Comlink.expose({
  ...,
  exposeMain(obj){
    main = obj;
  }
});
...
main.somethingOnMainThread(42);
```

That seems to work. Is this not a common use case? If so is there any point in adding it to the examples, or better still making some kind of slightly cleaner syntax for it?

Anyway, thanks for the help and for the nice package.

**Comment by surma** [comment]
> I see, that's a shame.

What is? What would you like to do that the approach above doesn’t allow you?

**Comment by MrMadClown** [comment]
> You just can’t mix the normal approach (exposing worker to main thread) with your approach (exposing main thread to worker).

@surma You can actually do that. 
I have a [PR](https://github.com/GoogleChromeLabs/comlink/pull/475) and an [Issue](https://github.com/GoogleChromeLabs/comlink/issues/474) open that makes it possible.
We've been using comlink with an Iframe that way since last June..

**Comment by d1manson** [comment]
@surma 
>  What would you like to do that the approach above doesn’t allow you?

i can accomplish what i need, and it's not terribly hard given i now know that you can't mix the two approaches.  
It's just that it seems 2-way communication could be a bit more straightforward or better documented.

@MrMadClown - thanks for the pointer, i will take a look

**Comment by pm-harshad-mane** [comment]
@MrMadClown waiting for your PR to merge.
