### ISSUE TITLE
Need help: any API that can help to worker get some data from main page

### ISSUE THREAD

**Issue by pm-harshad-mane** [GoogleChromeLabs/comlink#510]
Hello team,

Love your library, it really simplifies a lot of work.
I am new to the library, I see you have provided some cool APIs to call functions defined in worker from the main page.
Am wondering if I need to call a function defined in main page from the worker code?
Example:
# main.js
```
function getSomeTopLevelData(arg1, arg2){}
```

# worker.js
```
const topLevelData = Comlink.API.getSomeTopLevelData(arg1, arg2);
```

I see that call-backs for functions in main.js is a good option but i need it other way, whenever worker needs something(not available to worker) should be shared to worker as required(run-time value).

**Comment by pm-harshad-mane** [comment]
Hello @surma, @felixfbecker ,
Can you please help?

**Comment by surma** [comment]
You can just use Comlink “the other way around”. Take a look at [this](https://github.com/GoogleChromeLabs/comlink/issues/506#issuecomment-753457080). Does that help?

**Comment by pm-harshad-mane** [comment]
Thank you @surma !!
