### ISSUE TITLE
typescript remote doesn't work with class overloads

### ISSUE THREAD

**Issue by mathe42** [GoogleChromeLabs/comlink#511]
Small example:

```ts
import { Remote } from 'comlink'

class test {
  hello(a: string): string
  hello(a: number): number
  hello(a: number | string) {
    if (typeof a === 'number') {
      return a * a
    } else {
      return a
    }
  }
}

let b: Remote<test>

console.log(b.hello('test'), b.hello(5))
```

I expect this to compile without problems. But `b.hello('test')` throws an error. 'test' is not a number => not a valid argument.

Is there any way to fix this? Or is this a TS limitation?

Thanks in advance...

**Comment by felixfbecker** [comment]
Overloads are generally not possible to maintain with mapped types - a mapped type is a 1:1 mapping of methods, so it can't know ahead-of-time which overload to map. This is a limitation of TypeScript that I think we can't do anything about.

If you control the method, you can however often rewrite it to use union types without overloads. E.g. in your example just using `string | number`, and in more complex scenarios you can sometimes use union types of spreaded tuples, e.g. `method(...args: [arg1: number, arg2: number] | [arg1: string, arg2: string])`.

**Comment by mathe42** [comment]
Thanks! This helped.
