### ISSUE TITLE
RESULT_CODE_KILLED_BAD_MESSAGE when building a file Request in Chrome 89

### ISSUE THREAD

**Issue by KeithHenry** [GoogleChromeLabs/comlink#520]
I have a Comlink wrapper around a class that makes `fetch` requests, something like:

```ts
async postFiles(files: File[])
        const body = new FormData();
        for (const f of files)
            body.append('files', f, f.name);

        const uri = this.getUri();

        const request = new Request(uri, {
            method: 'POST',
            body,
            credentials: 'same-origin'
        });

        ...
```

When we get to `new Request(...` the tab crashes with `RESULT_CODE_KILLED_BAD_MESSAGE`

If we move this code out of Comlink and call it directly we get past creating the `Request` and can make the `fetch`.

This didn't happen in Chrome 88, but is happening now as our users upgrade to Chrome 89.

**Comment by surma** [comment]
It’s hard to tell or analyze without the full code. Can you put a reproduction example in a gist?

**Comment by KeithHenry** [comment]
@surma Here is a demo: https://jsfiddle.net/KeithHenry/hwzkg8ty/ choose a file and it crashes the `iframe` with `RESULT_CODE_KILLED_BAD_MESSAGE`

This seems to be enough to reproduce:

```html
<script id='worker' type='javascript/worker'>
importScripts('...comlink.js');

function postFiles(files) {
	if(!files)
  	return 0;

  const body = new FormData();
  for (const f of files)
    body.append('files', f, f.name);

  // RESULT_CODE_KILLED_BAD_MESSAGE thrown by next line
  const request = new Request('https://example.com', {
    method: 'POST',
    body,
    credentials: 'same-origin'
  });

  return 1;
}

Comlink.expose(postFiles);
</script>

<input id="fileSelect" type="file" multiple>

<script>
const blob = new Blob([document.getElementById('worker').textContent], {type: 'application/javascript'});
const worker = new Worker(window.URL.createObjectURL(blob), {
  name: 'Fetch Service'
});
const service = Comlink.wrap(worker);

const fileSelect = document.getElementById('fileSelect');
fileSelect.addEventListener('change', async e => {
  const fileList = fileSelect.files;
  await service(fileList);
})
</script>
```

**Comment by surma** [comment]
I don’t think this has anything to do with Comlink. A crash like that should never happen. I’d recommend filing a bug with [crbug.com/new](https://crbug.com/new).

Gonna close this for now, but if you think this is a Comlink issue, please feel encouraged to-reopen.

**Comment by KeithHenry** [comment]
@surma OK, I've raised https://bugs.chromium.org/p/chromium/issues/detail?id=1184680
