### ISSUE TITLE
4.3.1 stop working on production

### ISSUE THREAD

**Issue by dy-byron** [GoogleChromeLabs/comlink#537]
Hi, 
Since yesterday our projects that use Comlink stop working.

Downgrading the package solved the problem:
<img width="1182" alt="Screenshot 2021-05-13 at 09 54 34" src="https://user-images.githubusercontent.com/60141229/118096479-b1f39700-b3d1-11eb-83b9-37a91c199b34.png">

Is there anything in this 4.3.1 release that I should do for the workers?

Here's a simple example that was not working:
```js
importScripts("https://unpkg.com/comlink/dist/umd/comlink.js");

const ApiWorker = {
  fetch: async (url, options = {}) => {
    try {
      const res = await fetch(url, options)
      const json = await res.json()
      return [json, !res.ok]
    } catch (error) {
      console.warn('At api.worker.js -> ', error, url)
      return [error, true]
    }
  }
}

Comlink.expose(ApiWorker)
```

Debugging it looked like this promise never ended. No error, no feedback. Just didn't end. 
I tried the same code without the worker and it worked perfectly. 

Thanks,

**Edit**: Changing to 4.3.0 did also work
<img width="1165" alt="Screenshot 2021-05-13 at 10 37 01" src="https://user-images.githubusercontent.com/60141229/118101122-883d6e80-b3d7-11eb-8a82-ebedf6cf91ab.png">

**Comment by surma** [comment]
Huh, that is surprising. All the tests are still passing. I’ll take a look in the coming days. Thanks for flagging.

**Comment by surma** [comment]
Can you maybe provide a fully working code example? Which browser are you using?

I built a demo using your example and it works fine for me in Chrome, Firefox and Safari.

```html
<!doctype html>
<script src="https://unpkg.com/comlink/dist/umd/comlink.js"></script>
<script>  
async function main() {
  const worker = new Worker("./worker.js");
  const api = Comlink.wrap(worker);
  console.log(await api.fetch("/package.json"));
}
main();

</script>
```

```js
// worker.js
importScripts("https://unpkg.com/comlink/dist/umd/comlink.js");

const ApiWorker = {
  fetch: async (url, options = {}) => {
    try {
      const res = await fetch(url, options)
      const json = await res.json()
      return [json, !res.ok]
    } catch (error) {
      console.warn('At api.worker.js -> ', error, url)
      return [error, true]
    }
  }
}

Comlink.expose(ApiWorker)
```

![Screen Shot 2021-05-13 at 13 48 26](https://user-images.githubusercontent.com/234957/118127676-eaa36880-b3f1-11eb-865b-6dce3e484fdf.png)

**Comment by mecirmartin** [comment]
It also stopped working for us in prod, i personally am on `Chrome Version 90.0.4430.212 (Official Build) (arm64)`

**Comment by surma** [comment]
I’m really sorry to hear that some of you are experiencing breakage.

I just ran all the [examples](https://github.com/GoogleChromeLabs/comlink/tree/99165176eaa42eac0ae2f8748d9eca6f37830856/docs/examples) using Comlink v4.3.1 and they work as well for me. If anyone can give me a demo showing the breakage, I’d be very grateful, because I have nothing to go on as of now.

**Comment by MrMadClown** [comment]
Hi, I also upgraded to `v4.3.1` and I haven't had any problems yet. 

If you provide a breaking example, I'll help tackle the Issue.

**Comment by MrMadClown** [comment]
I have an Idea. Since we only saw the worker side which imports comlink via
`importScripts("https://unpkg.com/comlink/dist/umd/comlink.js");`
It might be the case that the main / window code is bundled in which case it still runs `v4.3.0` But `v4.3.0` and `v4.3.1` messages are incompatible due to the changed `MessageType`s 

I adapted @surma example, to test this theory and it does break in the described way.

```<!doctype html>
<script src="https://unpkg.com/comlink@4.3.0/dist/umd/comlink.js"></script>
<script>
  async function main() {
    const worker = new Worker("./worker.js");
    const api = Comlink.wrap(worker);
    console.log(await api.fetch("/package.json"));
  }
  main();

</script>
```

```// worker.js
importScripts("https://unpkg.com/comlink/dist/umd/comlink.js");

const ApiWorker = {
  fetch: async (url, options = {}) => {
    try {
      const res = await fetch(url, options)
      const json = await res.json()
      return [json, !res.ok]
    } catch (error) {
      console.warn('At api.worker.js -> ', error, url)
      return [error, true]
    }
  }
}

Comlink.expose(ApiWorker)
```

@dy-byron @mecirmartin can you confirm that your worker and window are running the same version of comlink?

**Comment by iguto** [comment]
hi, @dy-byron 
I had similar problem. in my case, worker was running with comlink@4.3.1, but main was running with 4.3.0.
After I update comlink version on main, worker works fine.
So you might need to update version on main.

I hope this helps.

**Comment by surma** [comment]
@iguto Thanks for that, that makes a lot of sense as an explanation. #475 changed data types, so the underlying RPC protocol changed, which would make 4.3.0 incompatible with 4.3.1. Tricky case, as the API remained stable and no new features were added (hence the patch version bump), but I guess there’s also a case to be made for this to be a minor version bump. Sorry for the confusion.

I’m gonna close this, but please re-open if this is not the explanation.

**Comment by dy-byron** [comment]
Thanks, @MrMadClown, @iguto, updating comlink on main solved the problem. 

Thanks everyone! 🙌

**Comment by mecirmartin** [comment]
@MrMadClown @iguto  Thanks, this helped!

**Comment by maksnester** [comment]
I have a case when a worker wrapped with complink lives in a separate npm package and uses comlink `4.3.0`, and I have a library that uses that worker with comlink. The library had a range version `^4.3.0`. So when a client app installs that library, it fetches comlink 4.3.1 and everything got broken 🙃 

> this to be a minor version bump 

@surma but breaking changes are supposed to change major version... Though #475 looks innocent and doesn't change API itself, it is still a literally breaking change as this issue shows.

**Comment by surma** [comment]
Please help me by weighing in at #540 on how to move forward on this issue.
