### ISSUE TITLE
Error: ERR_MODULE_NOT_FOUND esm\node-adapter

### ISSUE THREAD

**Issue by bennycode** [GoogleChromeLabs/comlink#541]
I want to use Comlink in a TypeScript project with Node.js. I have set "type" to "module" in my "package.json" and I set "module" to "ESNext" in my "tsconfig.json".

I am using Node v15 and ts-node v10. Both support ES modules but when I run my project it fails with the following error:

> Error: ERR_MODULE_NOT_FOUND C:\dev\projects\bennycode\tsnode-esm-test\node_modules\comlink\dist\esm\node-adapter C:\dev\projects\bennycode\tsnode-esm-test\src\start.ts module
> at finalizeResolution (C:\dev\projects\bennycode\tsnode-esm-test\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:380:11)
> at moduleResolve (C:\dev\projects\bennycode\tsnode-esm-test\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:815:10)
> at Object.defaultResolve (C:\dev\projects\bennycode\tsnode-esm-test\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:926:11)
> at C:\dev\projects\bennycode\tsnode-esm-test\node_modules\ts-node\src\esm.ts:67:38

Here is my code:

**src/worker.mjs**

```js
import { parentPort } from "worker_threads";
import nodeEndpoint from "comlink/dist/esm/node-adapter";

const api = {
  doMath() {
    return 4;
  }
};

expose(api, nodeEndpoint(parentPort));
```

**src/start.ts**

```ts
import { Worker } from "worker_threads";
import { wrap } from "comlink";
import nodeEndpoint from "comlink/dist/esm/node-adapter";

interface WorkerAPI {
  doMath: () => number
}

async function init() {
  const worker = new Worker("./worker.mjs");
  const api = wrap<WorkerAPI>(nodeEndpoint(worker));
  console.log(await api.doMath());
}

init();
```

I am running my code with the following command (per recommendation from https://github.com/TypeStrong/ts-node/issues/1007): 

```bash
node --loader ts-node/esm ./src/start.ts
```

You can find my test repo here:

- https://github.com/bennycode/tsnode-esm-test/tree/test-comlink

Am I missing a setup step?

Best,
Benny

**Comment by bennycode** [comment]
Today I built a sample which runs on plain JavaScript (no ts-node and no TypeScript). I am able to run it successfully when importing it the following way:

> import nodeEndpoint from "comlink/dist/esm/node-adapter.mjs";

When I drop the ".mjs" extension, then I get the error "ERR_MODULE_NOT_FOUND".

In my TypeScript code, I cannot import `node-adapter` with a `.mjs` extension because TypeScript does not support `.mjs` extensions yet (https://github.com/microsoft/TypeScript/issues/18442, https://github.com/microsoft/TypeScript/issues/27957):

> TS2307: Cannot find module 'comlink/dist/esm/node-adapter.mjs' or its corresponding type declarations.

Luckily, I was able to suppress that error to successfully import the `node-adapter`:

```ts
// @ts-ignore
import nodeEndpoint from "comlink/dist/esm/node-adapter.mjs";
```

So here is my full working example:

**Start Script**

```bash
node --loader ts-node/esm ./src/start-comlink.ts
```

**src/start-comlink.ts**

```ts
import { Worker } from "worker_threads";
import { wrap } from "comlink";
// @ts-ignore
import nodeEndpoint from "comlink/dist/esm/node-adapter.mjs";

interface WorkerAPI {
  doMath: () => number
}

async function init() {
  const worker = new Worker('./src/worker.mjs');
  const api = wrap<WorkerAPI>(nodeEndpoint(worker));
  console.log(await api.doMath());
  process.exit(0);
}

init();
```

**src/worker.mjs**

```js
import { parentPort } from "worker_threads";
import * as Comlink from "comlink";
import nodeEndpoint from "comlink/dist/esm/node-adapter.mjs";

const api = {
  doMath() {
    return 4;
  }
};

Comlink.expose(api, nodeEndpoint(parentPort));
```

@surma how about adding my findings (using MJS extension in combination with `@ts-ignore`) to the README?

**Comment by surma** [comment]
Yeah, that sounds like a good idea. Wanna open a PR?

**Comment by bennycode** [comment]
Yes. I will sum up the steps and open a PR later today. 🙂

**Comment by bennycode** [comment]
Here is my PR: https://github.com/GoogleChromeLabs/comlink/pull/542

Let's continue our discussion there. 😊
