### ISSUE TITLE
Awaiting the creation of the worker difference between 4.2.0 and ^4.3

### ISSUE THREAD

**Issue by ibsusu** [GoogleChromeLabs/comlink#544]
In 4.2 I'm able to await the creation of the worker, like so:
```javascript
    async function initWorker(){
          let url = '/js/worker.js';
          let started = false;
          for (let i=0;i<window.fullWorkerCount;++i){
            let worker = new Worker(url);
            let worker = window.comlink.wrap(worker);

            // The reason we're awaiting is to make sure that before we try to create anymore workers
            // we've cached the first worker's script.  otherwise the browser download them in parallel
            // which wastes tons of bandwidth
            window.workers.push(worker);
            let value = await window.workers[i].init();
            console.log("worker value", value);
          }
          window.workerCount = window.fullWorkerCount;
    }
```

But in 4.3 this is no longer possible.  Why is that?  I know I'm way behind on versions, I'm just trying to figure out why and how to get the previous functionality back or find a replacement for it.

**Comment by surma** [comment]
Are you using the same version of Comlink in the worker and the main thread file?

Can you provide a small reproduction case? Maybe in a gist or a throw-away repository?

**Comment by ibsusu** [comment]
You're entirely correct.  The reason was that the worker was loading 4.2.0 and the main thread file was loading 4.3.1.  Sorry to bother you with this.  I should've checked more thoroughly.  Thank you for your help and this great library.
