### ISSUE TITLE
How can i active worker again when t terminate it?

### ISSUE THREAD

**Issue by MinhPhuPham** [GoogleChromeLabs/comlink#546]
### I don't see documents for terminate when using with Vue framework. So i create a method right here, But when terminate it => it can't active when comeback.
So maybe can you help me in here.

Here is my Ex file:
`worker-api.js`: 
![image](https://user-images.githubusercontent.com/51711158/121806673-ff864c80-cc7a-11eb-8bbc-88486d62bca7.png)

`worker.js`:
![image](https://user-images.githubusercontent.com/51711158/121806691-14fb7680-cc7b-11eb-9db8-2c5d94eb050c.png)

My version: 
- web-loader: lasted
- comlink: lasted
- vue: ^2.6.12

**Comment by surma** [comment]
You can’t use/revive a worker once terminated. You need to create a new worker and call `wrap()` again.
