### ISSUE TITLE
Support Callbacks or Promises to pass an endpoint to "expose"

### ISSUE THREAD

**Issue by bennycode** [GoogleChromeLabs/comlink#549]
The `expose` function of `comlink` accepts an api object and an endpoint. By default, the `endpoint` is set to `self`. 

In my use case, I am writing TypeScript code which should run in a browser and Node.js environment. For this reason, I wrote a function which creates the endpoint based on the environment:

```ts
async function getEndpoint() {
  const inBrowser = typeof process !== "object";
  return inBrowser ? undefined : nodeEndpoint((await import("worker_threads")).parentPort);
}

expose(api, await getEndpoint());
```

Unfortunately, I am running intro troubles because my dynamic import of `worker_threads` forces my function `getEndpoint` to return a `Promise`. That in turn forces me to use `await` in my `expose` call which leads to problems if the environment doesn't support [top-level awaits](https://v8.dev/features/top-level-await).

Is it possible to enhance the `expose` function, so that it can resolve a `Promise` if it receives one?

**Comment by surma** [comment]
Is `getEndpoint().then(endpoint => expose(api, endpoint));` not sufficient for you?

**Comment by bennycode** [comment]
Sure, I can expose it this way. Just wanted to make this proposal for a more convenient API.

**Comment by surma** [comment]
It is fairly uncommon for web APIs to accept promises for the value they consume (WebAssembly is the odd exception here), so my current inclination is to not do this.

**Comment by bennycode** [comment]
Ok, fair enough!

**Comment by bennycode** [comment]
@surma I want to write code that runs in Node.js and modern web browsers. What do you think about providing small util functions for `expose` and `wrap` like these?

**getWorker**

```ts
export async function getWorker<API>(path: string): Promise<Remote<API>> {
  const workerConstructor = inBrowser ? Worker : (await import('worker_threads')).Worker;
  const worker = new workerConstructor(path);
  return wrap<API>(inBrowser ? worker : nodeEndpoint(worker));
}
```

**getEndpoint**

```ts
export async function getEndpoint() {
  const inBrowser = typeof process !== 'object';
  return inBrowser ? undefined : nodeEndpoint((await import('worker_threads')).parentPort);
}
```
