### ISSUE TITLE
rawValue.apply is not a function

### ISSUE THREAD

**Issue by rafalpawlow** [GoogleChromeLabs/comlink#571]
I'm trying to move huge class to be an web worker, and when i try to pass string to my class constructor I got this error:
`Uncaught (in promise) TypeError: rawValue.apply is not a function at MessagePort.callback`

It is triggered like this:
```
const worker = wrap(new Worker())
myClass = await new MyClass('endpoint')
```

What am I doing wrong?

**Comment by surma** [comment]
Can you put a reproducible example in a gist, StackBlitz or something?

**Comment by rafalpawlow** [comment]
hmmm not really, I wasn't able to get stackblitz to work with web workers. But in the meantime I discover this error comes from  `expose` function.
![Zrzut ekranu 2021-12-12 o 18 49 38](https://user-images.githubusercontent.com/13706246/145723646-51429346-a6ba-4ed4-a325-90720bde3cdb.png)

My worker looks like this:
```
import { expose } from 'comlink'

import { Api } from '@/utils/api'

export type ApiData = type of Api

expose(Api, self)
```

But this is correct way of using `expose`, right? In the screenshot from README file it looks the same.

**Comment by rafalpawlow** [comment]
Ok i figured it out. This error appears when I try set class instance to react state. Question: Is there a way to properly set class as a react state?
```
const worker = wrap(new Worker())
myClass = await new MyClass('endpoint')
setInstance(myClass)
```

**Comment by FL33TW00D** [comment]
To any future readers that find this, using a proxied class instance just doesn't work with `useState` for reasons still unknown.
However, it works perfectly fine with `useRef`.

**Comment by ivancuric** [comment]
@FL33TW00D Same goes for SolidJS' `createSignal` and other store methods:

https://stackblitz.com/edit/solidjs-templates-bc5cwn?file=src%2Fstore.ts,src%2FApp.tsx

I guess the main reason is that the exposed proxy that's being returned from `wrap` is not a proxy to an object, but a function for some reason. Frameworks read the `typeof` and try to call it.

**Comment by s-cork** [comment]
Since the proxy is a proxy function when you call setState. React will treat the argument as an updater rather then the next value in the state. So to fix this, whenever you try to set state on something that's been comlink proxied use an arrow function that returns the proxy. 

```js
setInstance(() => myClass)
```

Will work.

**Comment by fikrikarim** [comment]
I had the same problem, and the solution above fixed the issue: https://github.com/GoogleChromeLabs/comlink/issues/571#issuecomment-2048772957

Thank you!
