### ISSUE TITLE
Functions returned from worker aren't proxied, breaking `Observable`s

### ISSUE THREAD

**Issue by egasimus** [GoogleChromeLabs/comlink#573]
Encountered when using `zen-observable` and `zen-push` with `comlink` inside `vite`. Roughly speaking, the following happens:

```typescript
// Main.ts
import Worker from './Worker?worker'
const worker = Comlink.wrap(new Worker())
const observe = new Observable(observer=>worker.stream.observable.subscribe(Comlink.proxy(observer)))
```

```typescript
// Worker.ts
class WorkerImpl {
  stream = new PushStream()
  push (x) { this.stream.next(x) }
}

Comlink.expose(new WorkerImpl())
```

The problem is that `stream.observable.subscribe` returns an `unsubscribe` function back to main, and Comlink doesn't proxy it, so I get this error:

```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': function() {
  deleteObserver(p, observer);
  notifyPause(p, opts);
} could not be cloned.
    at http://localhost:3000/node_modules/.vite/comlink.js?v=e48a0bec:107:10
```

**Comment by surma** [comment]
Yes, if you want to return a function across a worker boundary, you have to wrap it with `Comlink.proxy()`. Please take a look at the [callback example](https://github.com/GoogleChromeLabs/comlink/tree/main/docs/examples/02-callback-example).

If you want to automatically proxy functions (not advised as it’s not necessarily cheap and can create unexpected memory leaks), use a transfer handler. Take a look at the [event listener example](https://github.com/GoogleChromeLabs/comlink/tree/main/docs/examples/04-eventlistener-example).

**Comment by egasimus** [comment]
@surma The both examples seem to demonstrate passing functions *into* the worker. I encountered this issue when trying to pass a function *out of* the worker. Is there an example that covers that?

**Comment by surma** [comment]
@egasimus It’s exactly the same. Comlink doesn’t care (or even know) which direction you are talking. Just wrap it in `Comlink.proxy()`

**Comment by egasimus** [comment]
@surma then what causes the error?
