### ISSUE TITLE
Jest test cases are failing

### ISSUE THREAD

**Issue by KVPasupuleti** [GoogleChromeLabs/comlink#578]
Hey @surma

1. I am using create-react-app, TypeScript, Craco (To override webpack) and Jest.
2. I figured out setting up Comlink by following @dominique-mueller 's [package](https://github.com/dominique-mueller/create-react-app-typescript-web-worker-setup) and got it working seamlessly.

But, I got an issue with Jest.

My class that will use this syntax `worker-loader!../Somefolder/worker.ts` will be exported initially with the App.tsx file.

So, while running Jest tests, all my tests are getting failed because of this.

I am getting this error while running Jest tests

```
Cannot find module 'worker-loader!../Somefolder/worker.ts' from 'src/xxx/xxx/xxx/xxx/index.ts'
```

I have followed [this](https://github.com/webpack-contrib/worker-loader/issues/10#issuecomment-325977537) solution. This has resolved the problem, but I got another issue like this

```
TypeError: ep.addEventListener is not a function
```

I believe this is not a duplicate of [this](https://github.com/GoogleChromeLabs/comlink/issues/503)

Could you please look into this and suggest a solution?

**Comment by Chatlead-RupanjanHari** [comment]
I have the exact same problem with the same configuration

**Comment by KVPasupuleti** [comment]
Hey @Chatlead-RupanjanHari 

As Web workers aren't available in the Jest context, we have skipped this issue by mocking the file containing the above-stated import statement.

**Comment by Chatlead-RupanjanHari** [comment]
Can you show me a snippet of the solution you are talking about.

Because, I am trying the 'moduleNameMapper' way...but, that doesn't seem to work.

**Comment by benjamind** [comment]
Closing as won't fix as this is a Jest issue.

**Comment by nishatsayyed** [comment]
@Chatlead-RupanjanHari Did you find a solution for this? The issue seem to have been closed without a proper solution.

**Comment by MoldyLunchBox** [comment]
why did you close this. i could desperately use a tip or a solution
