### ISSUE TITLE
Comlink + Webpack 5 setup

### ISSUE THREAD

**Issue by dvago** [GoogleChromeLabs/comlink#580]
Hi there,

I know there is already an open request #565 related to this argument but I think it must be a bit more generic.
Would you be able to provide an official example on how to use Comlink with Webpack 5 please?

As we all know, **worker-loader** has been deprecated in favour of the native way to import workers, but then it means **comlink-loader** is deprecated as well.

**Comment by SumanX22** [comment]
React 17(webpack 5) and Comlink needs address

**Comment by benjamind** [comment]
Haven't had any specific problems with using webpack v5 and comlink, here's an [example sandbox](https://codesandbox.io/p/sandbox/aged-dream-3yn2dm?file=%2Fsrc%2Findex.ts&selection=%5B%7B%22endColumn%22%3A4%2C%22endLineNumber%22%3A10%2C%22startColumn%22%3A4%2C%22startLineNumber%22%3A10%7D%5D)

**Comment by benjamind** [comment]
Closing as duplicate of #565
