### ISSUE TITLE
Upcoming new version?

### ISSUE THREAD

**Issue by CodeWithOz** [GoogleChromeLabs/comlink#591]
Is there an upcoming newer version of this package any time soon? I can there've been commits in the master branch going back to last year, so I'd like to know if there's a new release planned. I would prefer to install a published version from npm than the latest state of the master branch. Thanks.

**Comment by rracariu** [comment]
There are some PRs that should get in, like https://github.com/GoogleChromeLabs/comlink/pull/569 which fixes an issue I care about, and scanning the PR list others address issues also.

I would say a release would be nice to have, but I think this project doesn't have an active maintainer anymore, the one mentioned in the release pages looks to not work at Google anymore.

@surma can you please comment on this?

**Comment by benjamind** [comment]
Have volunteered to help out Surma here, will be trying to get a new version out with a bunch of these PRs in the next few days.

**Comment by garethj2** [comment]
It's great to see activity on this repo again.

Just out of interest, when will a new release happen? The last release was two years ago and it seems there's plenty of activity on master.

**Comment by benjamind** [comment]
Published 4.4.0 today! Please let us know if there's any issues.
