### ISSUE TITLE
Possible to communicate between web workers?

### ISSUE THREAD

**Issue by rheanV** [GoogleChromeLabs/comlink#640]
Worker 2 needs to access an object from worker 1. Is this possible?

**Comment by benjamind** [comment]
Yes, you can accomplish this in a number of ways. The most ergonomic I think is to create a MessageChannel in one or other of the workers (or in main), and then pass its ports to each of the workers (either via Comlink interfaces, or just as postMessage handlers). Then inside those workers create Comlink endpoints on either side of the message channel. You can then communicate directly between the workers.
