### ISSUE TITLE
Do I need to use transfer inside a proxy?

### ISSUE THREAD

**Issue by Tsury** [GoogleChromeLabs/comlink#645]
Sorry for making an issue - was unable to find an answer.

My main creates a worker, and sends some callback to it wrapped in a proxy.
Said callback needs to pass back to main a very big array.

Do I need to transfer the array, even though the callback is a proxy?

Thanks.

**Comment by benjamind** [comment]
I believe so yes. Any time you pass a value that you want to transfer rather than clone then you'll need to transfer it.
